## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('mlprovenance', ['internet-stack'])
    module.source = [
        'mlprovenance.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'mlprovenance'
    headers.source = [
        'mlprovenance.h',
        'mlprovenance-helper.h',
        ]
