## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pktfwd-norm-bdfair', ['internet-stack'])
    module.source = [
        'pktfwd-norm-bdfair.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pktfwd-norm-bdfair'
    headers.source = [
        'pktfwd-norm-bdfair.h',
        'pktfwd-norm-bdfair-helper.h',
        ]
