## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('firewall-weak', ['internet-stack'])
    module.source = [
        'firewall-weak.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'firewall-weak'
    headers.source = [
        'firewall-weak.h',
        'firewall-weak-helper.h',
        ]
