## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pktfwd-online-bcast-slowchange-update', ['internet-stack'])
    module.source = [
        'pktfwd-online-bcast-slowchange-update.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pktfwd-online-bcast-slowchange-update'
    headers.source = [
        'pktfwd-online-bcast-slowchange-update.h',
        'pktfwd-online-bcast-slowchange-update-helper.h',
        ]
