/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef PKTFWDNORMPROVRULEAUXTABLEQUERY_H
#define PKTFWDNORMPROVRULEAUXTABLEQUERY_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace pktfwdnormprovruleauxtablequery {

class PktfwdNormProvRuleauxtableQuery : public RapidNetApplicationBase
{
public:
  static const string EPRETURN;
  static const string EPROVQUERY;
  static const string ERRETURN;
  static const string ERULEQUERY;
  static const string EPACKET;
  static const string EPACKETTEMP;
  static const string ERECVPACKET;
  static const string ERECVPACKETTEMP;
  static const string FLOWENTRY;
  static const string INITPACKET;
  static const string LINK;
  static const string PITERATE;
  static const string PQLIST;
  static const string PRESULTTMP;
  static const string PRETURN;
  static const string PACKET;
  static const string PROV;
  static const string PROVQUERY;
  static const string PROVSTR;
  static const string RITERATE;
  static const string RQLIST;
  static const string RRESULTTMP;
  static const string RRETURN;
  static const string RECORDRULE;
  static const string RECVPACKET;
  static const string RULEEXEC;
  static const string RULEINFO;
  static const string RULEQUERY;

  static TypeId GetTypeId (void);

  PktfwdNormProvRuleauxtableQuery ();

  virtual ~PktfwdNormProvRuleauxtableQuery ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void Rr01Eca0Ins (Ptr<Tuple> recordRule);

  virtual void Rr01Eca0Del (Ptr<Tuple> recordRule);

  virtual void Rr02Eca0Ins (Ptr<Tuple> recordRule);

  virtual void Rr02Eca0Del (Ptr<Tuple> recordRule);

  virtual void Rr03Eca0Ins (Ptr<Tuple> recordRule);

  virtual void Rr03Eca0Del (Ptr<Tuple> recordRule);

  virtual void R00Eca1Ins (Ptr<Tuple> initPacket);

  virtual void R00Eca1Del (Ptr<Tuple> initPacket);

  virtual void Prov_r00Eca0Ins (Ptr<Tuple> initPacket);

  virtual void Prov_r00Eca0Del (Ptr<Tuple> initPacket);

  virtual void R01Eca1Ins (Ptr<Tuple> link);

  virtual void R01Eca1Del (Ptr<Tuple> link);

  virtual void Prov_r01Eca0Ins (Ptr<Tuple> link);

  virtual void Prov_r01Eca0Del (Ptr<Tuple> link);

  virtual void R03Eca1Ins (Ptr<Tuple> flowEntry);

  virtual void R03Eca1Del (Ptr<Tuple> flowEntry);

  virtual void Prov_r03Eca0Ins (Ptr<Tuple> flowEntry);

  virtual void Prov_r03Eca0Del (Ptr<Tuple> flowEntry);

  virtual void Prov_rs1_1_eca (Ptr<Tuple> packet);

  virtual void Prov_rs1_2_eca (Ptr<Tuple> epacketTemp);

  virtual void Prov_rs1_3_eca (Ptr<Tuple> epacketTemp);

  virtual void Prov_rs1_4_eca (Ptr<Tuple> epacket);

  virtual void Prov_rs1_5_eca (Ptr<Tuple> epacket);

  virtual void Prov_rs1_6_eca (Ptr<Tuple> epacket);

  virtual void Prov_rh1_1Eca0Ins (Ptr<Tuple> initPacket);

  virtual void Prov_rh1_1Eca1Ins (Ptr<Tuple> link);

  virtual void Prov_rh2_1_eca (Ptr<Tuple> packet);

  virtual void Prov_rh2_2_eca (Ptr<Tuple> erecvPacketTemp);

  virtual void Prov_rh2_3_eca (Ptr<Tuple> erecvPacketTemp);

  virtual void Prov_rh2_4_eca (Ptr<Tuple> erecvPacket);

  virtual void Prov_rh2_5_eca (Ptr<Tuple> erecvPacket);

  virtual void Prov_rh2_6_eca (Ptr<Tuple> erecvPacket);

  virtual void Edb1_eca (Ptr<Tuple> provQuery);

  virtual void Idb1_eca (Ptr<Tuple> provQuery);

  virtual void Idb2_eca (Ptr<Tuple> provQuery);

  virtual void Idb3_eca (Ptr<Tuple> provQuery);

  virtual void Idb4_eca (Ptr<Tuple> pIterate);

  virtual void Idb5_eca (Ptr<Tuple> pIterate);

  virtual void Idb6_eca (Ptr<Tuple> eRuleQuery);

  virtual void Idb7_eca (Ptr<Tuple> rReturn);

  virtual void Idb8Eca0Ins (Ptr<Tuple> pResultTmp);

  virtual void Idb8Eca1Ins (Ptr<Tuple> pQList);

  virtual void Idb9_eca (Ptr<Tuple> ePReturn);

  virtual void Rv1_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv2_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv3_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv4_eca (Ptr<Tuple> rIterate);

  virtual void Rv5_eca (Ptr<Tuple> rIterate);

  virtual void Rv6_eca (Ptr<Tuple> eProvQuery);

  virtual void Rv7_eca (Ptr<Tuple> pReturn);

  virtual void Rv8Eca0Ins (Ptr<Tuple> rResultTmp);

  virtual void Rv8Eca1Ins (Ptr<Tuple> rQList);

  virtual void Rv9_eca (Ptr<Tuple> eRReturn);

};

} // namespace pktfwdnormprovruleauxtablequery
} // namespace rapidnet
} // namespace ns3

#endif // PKTFWDNORMPROVRULEAUXTABLEQUERY_H
