## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pktfwd-norm-prov-ruleauxtable-query', ['internet-stack'])
    module.source = [
        'pktfwd-norm-prov-ruleauxtable-query.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pktfwd-norm-prov-ruleauxtable-query'
    headers.source = [
        'pktfwd-norm-prov-ruleauxtable-query.h',
        'pktfwd-norm-prov-ruleauxtable-query-helper.h',
        ]
