/* A RapidNet application. Generated by RapidNet compiler. */

#include "pktfwd-norm-dhlist-layerhs-online.h"
#include <cstdlib>
#include "ns3/nstime.h"
#include "ns3/simulator.h"
#include "ns3/type-ids.h"
#include "ns3/rapidnet-types.h"
#include "ns3/rapidnet-utils.h"
#include "ns3/assignor.h"
#include "ns3/selector.h"
#include "ns3/rapidnet-functions.h"

using namespace std;
using namespace ns3;
using namespace ns3::rapidnet;
using namespace ns3::rapidnet::pktfwdnormdhlistlayerhsonline;

const string PktfwdNormDhlistLayerhsOnline::EPACKETCOUNT = "epacketCount";
const string PktfwdNormDhlistLayerhsOnline::EPACKETTEMP = "epacketTemp";
const string PktfwdNormDhlistLayerhsOnline::EQUIHASHTABLE = "equiHashTable";
const string PktfwdNormDhlistLayerhsOnline::ERECVPACKETTEMP = "erecvPacketTemp";
const string PktfwdNormDhlistLayerhsOnline::FLOWENTRY = "flowEntry";
const string PktfwdNormDhlistLayerhsOnline::INITPACKET = "initPacket";
const string PktfwdNormDhlistLayerhsOnline::INITPACKETCOUNT = "initPacketCount";
const string PktfwdNormDhlistLayerhsOnline::INITPACKETHASH = "initPacketHash";
const string PktfwdNormDhlistLayerhsOnline::LINK = "link";
const string PktfwdNormDhlistLayerhsOnline::PACKET = "packet";
const string PktfwdNormDhlistLayerhsOnline::PACKETPROV = "packetProv";
const string PktfwdNormDhlistLayerhsOnline::PROGRAMID = "programID";
const string PktfwdNormDhlistLayerhsOnline::PROVHASHTABLE = "provHashTable";
const string PktfwdNormDhlistLayerhsOnline::PROVLINK = "provLink";
const string PktfwdNormDhlistLayerhsOnline::RECVPACKET = "recvPacket";
const string PktfwdNormDhlistLayerhsOnline::RECVPACKETPROV = "recvPacketProv";
const string PktfwdNormDhlistLayerhsOnline::RECVPACKETQRY = "recvPacketQry";
const string PktfwdNormDhlistLayerhsOnline::RULEEXEC = "ruleExec";

NS_LOG_COMPONENT_DEFINE ("PktfwdNormDhlistLayerhsOnline");
NS_OBJECT_ENSURE_REGISTERED (PktfwdNormDhlistLayerhsOnline);

TypeId
PktfwdNormDhlistLayerhsOnline::GetTypeId (void)
{
  static TypeId tid = TypeId ("ns3::rapidnet::pktfwdnormdhlistlayerhsonline::PktfwdNormDhlistLayerhsOnline")
    .SetParent<RapidNetApplicationBase> ()
    .AddConstructor<PktfwdNormDhlistLayerhsOnline> ()
    ;
  return tid;
}

PktfwdNormDhlistLayerhsOnline::PktfwdNormDhlistLayerhsOnline()
{
  NS_LOG_FUNCTION_NOARGS ();
}

PktfwdNormDhlistLayerhsOnline::~PktfwdNormDhlistLayerhsOnline()
{
  NS_LOG_FUNCTION_NOARGS ();
}

void
PktfwdNormDhlistLayerhsOnline::DoDispose (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::DoDispose ();
}

void
PktfwdNormDhlistLayerhsOnline::StartApplication (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StartApplication ();
  RAPIDNET_LOG_INFO("PktfwdNormDhlistLayerhsOnline Application Started");
}

void
PktfwdNormDhlistLayerhsOnline::StopApplication ()
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StopApplication ();
  RAPIDNET_LOG_INFO("PktfwdNormDhlistLayerhsOnline Application Stopped");
}

void
PktfwdNormDhlistLayerhsOnline::InitDatabase ()
{
  //RapidNetApplicationBase::InitDatabase ();

  AddRelationWithKeys (EQUIHASHTABLE, attrdeflist (
    attrdef ("equiHashTable_attr2", IPV4)));

  AddRelationWithKeys (FLOWENTRY, attrdeflist (
    attrdef ("flowEntry_attr2", IPV4)));

  AddRelationWithKeys (INITPACKET, attrdeflist (
    attrdef ("initPacket_attr2", IPV4),
    attrdef ("initPacket_attr3", IPV4),
    attrdef ("initPacket_attr4", STR)));

  AddRelationWithKeys (LINK, attrdeflist (
    attrdef ("link_attr2", IPV4)));

  AddRelationWithKeys (PROGRAMID, attrdeflist (
    attrdef ("programID_attr2", IPV4)));

  AddRelationWithKeys (PROVHASHTABLE, attrdeflist (
    attrdef ("provHashTable_attr3", LIST)));

  AddRelationWithKeys (PROVLINK, attrdeflist (
    attrdef ("provLink_attr2", ID),
    attrdef ("provLink_attr3", INT32),
    attrdef ("provLink_attr4", IPV4),
    attrdef ("provLink_attr5", ID),
    attrdef ("provLink_attr6", INT32)));

  AddRelationWithKeys (RECVPACKET, attrdeflist (
    attrdef ("recvPacket_attr2", IPV4),
    attrdef ("recvPacket_attr3", IPV4),
    attrdef ("recvPacket_attr4", STR)));

  AddRelationWithKeys (RECVPACKETQRY, attrdeflist (
    attrdef ("recvPacketQry_attr2", ID)));

  AddRelationWithKeys (RULEEXEC, attrdeflist (
    attrdef ("ruleExec_attr2", ID)));

}

void
PktfwdNormDhlistLayerhsOnline::DemuxRecv (Ptr<Tuple> tuple)
{
  RapidNetApplicationBase::DemuxRecv (tuple);

  if (IsRecvEvent (tuple, PACKETPROV))
    {
      Prov_rs1_1_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPACKETTEMP))
    {
      Prov_rs1_2_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPACKETCOUNT))
    {
      Prov_rs1_3_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPACKETTEMP))
    {
      Prov_rs1_4_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPACKETTEMP))
    {
      Prov_rs1_5_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKET))
    {
      Rs1_eca (tuple);
    }
  if (IsInsertEvent (tuple, INITPACKET))
    {
      Prov_ri1Eca0Ins (tuple);
    }
  if (IsInsertEvent (tuple, PROGRAMID))
    {
      Prov_ri1Eca1Ins (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETHASH))
    {
      Prov_ri2_eca (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETCOUNT))
    {
      Prov_ri3_eca (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETCOUNT))
    {
      Rh1_eca (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETCOUNT))
    {
      Prov_rh1_1_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKETPROV))
    {
      Prov_rh2_1_eca (tuple);
    }
  if (IsRecvEvent (tuple, ERECVPACKETTEMP))
    {
      Prov_rh2_2_eca (tuple);
    }
  if (IsRecvEvent (tuple, ERECVPACKETTEMP))
    {
      Prov_rh2_4_eca (tuple);
    }
  if (IsRecvEvent (tuple, ERECVPACKETTEMP))
    {
      Prov_rh2_5_eca (tuple);
    }
  if (IsRecvEvent (tuple, RECVPACKETPROV))
    {
      Prov_rh2_6_eca (tuple);
    }
  if (IsRecvEvent (tuple, RECVPACKETPROV))
    {
      Ro1_eca (tuple);
    }
  if (IsRecvEvent (tuple, RECVPACKETPROV))
    {
      Ro2_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKET))
    {
      Rh2_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKET))
    {
      Rho3_eca (tuple);
    }
}

void
PktfwdNormDhlistLayerhsOnline::Prov_rs1_1_eca (Ptr<Tuple> packetProv)
{
  RAPIDNET_LOG_INFO ("Prov_rs1_1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (FLOWENTRY)->Join (
    packetProv,
    strlist ("flowEntry_attr2", "flowEntry_attr1"),
    strlist ("packetProv_attr3", "packetProv_attr1"));

  result = GetRelation (LINK)->Join (
    result,
    strlist ("link_attr2", "link_attr1"),
    strlist ("flowEntry_attr3", "packetProv_attr1"));

  result->Assign (Assignor::New ("PID3",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            ValueExpr::New (StrValue::New ("flowEntry")),
            VarExpr::New ("packetProv_attr1")),
          VarExpr::New ("packetProv_attr3")),
        VarExpr::New ("flowEntry_attr3")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID3"))));

  result->Assign (Assignor::New ("PID4",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("link")),
          VarExpr::New ("packetProv_attr1")),
        VarExpr::New ("flowEntry_attr3")))));

  result->Assign (Assignor::New ("List4",
    FAppend::New (
      VarExpr::New ("PID4"))));

  result->Assign (Assignor::New ("List",
    FConcat::New (
      VarExpr::New ("List"),
      VarExpr::New ("List4"))));

  result->Assign (Assignor::New ("RLOC",
    VarExpr::New ("packetProv_attr1")));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rs1"))));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("R"),
        VarExpr::New ("List")))));

  result = result->Project (
    EPACKETTEMP,
    strlist ("RLOC",
      "flowEntry_attr3",
      "packetProv_attr2",
      "packetProv_attr3",
      "packetProv_attr4",
      "RID",
      "R",
      "List",
      "packetProv_attr5",
      "RLOC"),
    strlist ("epacketTemp_attr1",
      "epacketTemp_attr2",
      "epacketTemp_attr3",
      "epacketTemp_attr4",
      "epacketTemp_attr5",
      "epacketTemp_attr6",
      "epacketTemp_attr7",
      "epacketTemp_attr8",
      "epacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_rs1_2_eca (Ptr<Tuple> epacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rs1_2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (RULEEXEC)->Join (
    epacketTemp,
    strlist ("ruleExec_attr4", "ruleExec_attr3", "ruleExec_attr2", "ruleExec_attr1"),
    strlist ("epacketTemp_attr8", "epacketTemp_attr7", "epacketTemp_attr6", "epacketTemp_attr1"));

  result = AggWrapCount::New ()->Compute (result, epacketTemp);

  result = result->Project (
    EPACKETCOUNT,
    strlist ("epacketTemp_attr1",
      "epacketTemp_attr6",
      "epacketTemp_attr7",
      "epacketTemp_attr8",
      "count"),
    strlist ("epacketCount_attr1",
      "epacketCount_attr2",
      "epacketCount_attr3",
      "epacketCount_attr4",
      "epacketCount_attr5"));

  SendLocal (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_rs1_3_eca (Ptr<Tuple> epacketCount)
{
  RAPIDNET_LOG_INFO ("Prov_rs1_3_eca triggered");

  Ptr<Tuple> result = epacketCount;

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("epacketCount_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    RULEEXEC,
    strlist ("epacketCount_attr1",
      "epacketCount_attr2",
      "epacketCount_attr3",
      "epacketCount_attr4"),
    strlist ("ruleExec_attr1",
      "ruleExec_attr2",
      "ruleExec_attr3",
      "ruleExec_attr4"));

  Insert (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_rs1_4_eca (Ptr<Tuple> epacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rs1_4_eca triggered");

  Ptr<Tuple> result = epacketTemp;

  result->Assign (Assignor::New ("Preloc",
    FFirst::New (
      VarExpr::New ("epacketTemp_attr9"))));

  result->Assign (Assignor::New ("TempTag1",
    FRemoveFirst::New (
      VarExpr::New ("epacketTemp_attr9"))));

  result->Assign (Assignor::New ("PreRID",
    FFirst::New (
      VarExpr::New ("TempTag"))));

  result->Assign (Assignor::New ("TempTag2",
    FRemoveFirst::New (
      VarExpr::New ("TempTag1"))));

  result->Assign (Assignor::New ("PreLhash",
    FFirst::New (
      VarExpr::New ("TempTag2"))));

  result->Assign (Assignor::New ("TempTag3",
    FRemoveFirst::New (
      VarExpr::New ("TempTag2"))));

  result->Assign (Assignor::New ("ProgID",
    FFirst::New (
      VarExpr::New ("TempTag3"))));

  result->Assign (Assignor::New ("CurLhash",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("PreLhash"),
        VarExpr::New ("epacketTemp_attr6")))));

  result = result->Project (
    PROVLINK,
    strlist ("epacketTemp_attr1",
      "ProgID",
      "epacketTemp_attr6",
      "CurLhash",
      "Preloc",
      "PreRID",
      "PreLhash"),
    strlist ("provLink_attr1",
      "provLink_attr2",
      "provLink_attr3",
      "provLink_attr4",
      "provLink_attr5",
      "provLink_attr6",
      "provLink_attr7"));

  Insert (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_rs1_5_eca (Ptr<Tuple> epacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rs1_5_eca triggered");

  Ptr<Tuple> result = epacketTemp;

  result->Assign (Assignor::New ("TempNewTag1",
    FRemoveFirst::New (
      VarExpr::New ("epacketTemp_attr9"))));

  result->Assign (Assignor::New ("TempNewTag2",
    FRemoveFirst::New (
      VarExpr::New ("TempNewTag1"))));

  result->Assign (Assignor::New ("PreLhash",
    FFirst::New (
      VarExpr::New ("TempNewTag2"))));

  result->Assign (Assignor::New ("CurLhash",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("PreLhash"),
        VarExpr::New ("epacketTemp_attr6")))));

  result->Assign (Assignor::New ("CurLhashlist",
    FAppend::New (
      VarExpr::New ("CurLhashlist"))));

  result->Assign (Assignor::New ("TempNewTag3",
    FRemoveFirst::New (
      VarExpr::New ("TempNewTag2"))));

  result->Assign (Assignor::New ("RIDlist",
    FAppend::New (
      VarExpr::New ("epacketTemp_attr6"))));

  result->Assign (Assignor::New ("Loclist",
    FAppend::New (
      VarExpr::New ("epacketTemp_attr1"))));

  result->Assign (Assignor::New ("TempNewTag4",
    FConcat::New (
      VarExpr::New ("CurLhashlist"),
      VarExpr::New ("TempNewTag3"))));

  result->Assign (Assignor::New ("TempNewTag5",
    FConcat::New (
      VarExpr::New ("RIDlist"),
      VarExpr::New ("TempNewTag4"))));

  result->Assign (Assignor::New ("NewTag",
    FConcat::New (
      VarExpr::New ("Loclist"),
      VarExpr::New ("TempNewTag5"))));

  result = result->Project (
    PACKETPROV,
    strlist ("epacketTemp_attr2",
      "epacketTemp_attr3",
      "epacketTemp_attr4",
      "epacketTemp_attr5",
      "NewTag",
      "epacketTemp_attr2"),
    strlist ("packetProv_attr1",
      "packetProv_attr2",
      "packetProv_attr3",
      "packetProv_attr4",
      "packetProv_attr5",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDhlistLayerhsOnline::Rs1_eca (Ptr<Tuple> packet)
{
  RAPIDNET_LOG_INFO ("Rs1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (FLOWENTRY)->Join (
    packet,
    strlist ("flowEntry_attr2", "flowEntry_attr1"),
    strlist ("packet_attr3", "packet_attr1"));

  result = GetRelation (LINK)->Join (
    result,
    strlist ("link_attr2", "link_attr1"),
    strlist ("flowEntry_attr3", "packet_attr1"));

  result = result->Project (
    PACKET,
    strlist ("flowEntry_attr3",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "packet_attr5",
      "flowEntry_attr3"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "packet_attr5",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_ri1Eca0Ins (Ptr<Tuple> initPacket)
{
  RAPIDNET_LOG_INFO ("Prov_ri1Eca0Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (PROGRAMID)->Join (
    initPacket,
    strlist ("programID_attr2", "programID_attr1"),
    strlist ("initPacket_attr3", "initPacket_attr1"));

  result->Assign (Assignor::New ("PIDequi",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("")),
          VarExpr::New ("initPacket_attr1")),
        VarExpr::New ("initPacket_attr3")))));

  result = result->Project (
    INITPACKETHASH,
    strlist ("initPacket_attr1",
      "initPacket_attr2",
      "initPacket_attr3",
      "initPacket_attr4",
      "PIDequi",
      "programID_attr3"),
    strlist ("initPacketHash_attr1",
      "initPacketHash_attr2",
      "initPacketHash_attr3",
      "initPacketHash_attr4",
      "initPacketHash_attr5",
      "initPacketHash_attr6"));

  SendLocal (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_ri1Eca1Ins (Ptr<Tuple> programID)
{
  RAPIDNET_LOG_INFO ("Prov_ri1Eca1Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (INITPACKET)->Join (
    programID,
    strlist ("initPacket_attr3", "initPacket_attr1"),
    strlist ("programID_attr2", "programID_attr1"));

  result->Assign (Assignor::New ("PIDequi",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("")),
          VarExpr::New ("programID_attr1")),
        VarExpr::New ("programID_attr2")))));

  result = result->Project (
    INITPACKETHASH,
    strlist ("programID_attr1",
      "initPacket_attr2",
      "programID_attr2",
      "initPacket_attr4",
      "PIDequi",
      "programID_attr3"),
    strlist ("initPacketHash_attr1",
      "initPacketHash_attr2",
      "initPacketHash_attr3",
      "initPacketHash_attr4",
      "initPacketHash_attr5",
      "initPacketHash_attr6"));

  SendLocal (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_ri2_eca (Ptr<Tuple> initPacketHash)
{
  RAPIDNET_LOG_INFO ("Prov_ri2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (EQUIHASHTABLE)->Join (
    initPacketHash,
    strlist ("equiHashTable_attr2", "equiHashTable_attr1", "equiHashTable_attr3"),
    strlist ("initPacketHash_attr3", "initPacketHash_attr1", "initPacketHash_attr5"));

  result = AggWrapCount::New ()->Compute (result, initPacketHash);

  result = result->Project (
    INITPACKETCOUNT,
    strlist ("initPacketHash_attr1",
      "initPacketHash_attr2",
      "initPacketHash_attr3",
      "initPacketHash_attr4",
      "initPacketHash_attr5",
      "initPacketHash_attr6",
      "count"),
    strlist ("initPacketCount_attr1",
      "initPacketCount_attr2",
      "initPacketCount_attr3",
      "initPacketCount_attr4",
      "initPacketCount_attr5",
      "initPacketCount_attr6",
      "initPacketCount_attr7"));

  SendLocal (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_ri3_eca (Ptr<Tuple> initPacketCount)
{
  RAPIDNET_LOG_INFO ("Prov_ri3_eca triggered");

  Ptr<Tuple> result = initPacketCount;

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("initPacketCount_attr7"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    EQUIHASHTABLE,
    strlist ("initPacketCount_attr1",
      "initPacketCount_attr3",
      "initPacketCount_attr5"),
    strlist ("equiHashTable_attr1",
      "equiHashTable_attr2",
      "equiHashTable_attr3"));

  Insert (result);
}

void
PktfwdNormDhlistLayerhsOnline::Rh1_eca (Ptr<Tuple> initPacketCount)
{
  RAPIDNET_LOG_INFO ("Rh1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (LINK)->Join (
    initPacketCount,
    strlist ("link_attr1"),
    strlist ("initPacketCount_attr1"));

  result->Assign (Assignor::New ("PIDev",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("initPacket")),
              VarExpr::New ("initPacketCount_attr1")),
            VarExpr::New ("initPacketCount_attr2")),
          VarExpr::New ("initPacketCount_attr3")),
        VarExpr::New ("initPacketCount_attr4")))));

  result->Assign (Assignor::New ("PIDequiHash",
    FAppend::New (
      VarExpr::New ("initPacketCount_attr5"))));

  result->Assign (Assignor::New ("PIDevHash",
    FAppend::New (
      VarExpr::New ("PIDev"))));

  result->Assign (Assignor::New ("ProgIDlist",
    FAppend::New (
      VarExpr::New ("initPacketCount_attr6"))));

  result->Assign (Assignor::New ("PIDHash1",
    FConcat::New (
      VarExpr::New ("PIDequiHash"),
      VarExpr::New ("PIDevHash"))));

  result->Assign (Assignor::New ("PIDHash",
    FConcat::New (
      VarExpr::New ("PIDHash1"),
      VarExpr::New ("ProgIDlist"))));

  result = result->Select (Selector::New (
    Operation::New (RN_NEQ,
      VarExpr::New ("initPacketCount_attr7"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    PACKET,
    strlist ("link_attr2",
      "initPacketCount_attr2",
      "initPacketCount_attr3",
      "initPacketCount_attr4",
      "PIDHash",
      "link_attr2"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "packet_attr5",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_rh1_1_eca (Ptr<Tuple> initPacketCount)
{
  RAPIDNET_LOG_INFO ("Prov_rh1_1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (LINK)->Join (
    initPacketCount,
    strlist ("link_attr1"),
    strlist ("initPacketCount_attr1"));

  result->Assign (Assignor::New ("PID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("link")),
          VarExpr::New ("initPacketCount_attr1")),
        VarExpr::New ("link_attr2")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID"))));

  result->Assign (Assignor::New ("RLOC",
    VarExpr::New ("initPacketCount_attr1")));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("R"),
        VarExpr::New ("List")))));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rh1"))));

  result->Assign (Assignor::New ("Equilist",
    FAppend::New (
      VarExpr::New ("initPacketCount_attr5"))));

  result->Assign (Assignor::New ("PIDev",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("initPacket")),
              VarExpr::New ("initPacketCount_attr1")),
            VarExpr::New ("initPacketCount_attr2")),
          VarExpr::New ("initPacketCount_attr3")),
        VarExpr::New ("initPacketCount_attr4")))));

  result->Assign (Assignor::New ("Evlist",
    FAppend::New (
      VarExpr::New ("PIDev"))));

  result->Assign (Assignor::New ("ProgIDlist",
    FAppend::New (
      VarExpr::New ("initPacketCount_attr6"))));

  result->Assign (Assignor::New ("InitLhashlist",
    FAppend::New (
      ValueExpr::New (StrValue::New ("NULL")))));

  result->Assign (Assignor::New ("InitProvNode",
    VarExpr::New ("RLOC")));

  result->Assign (Assignor::New ("InitProvNodelist",
    FAppend::New (
      VarExpr::New ("InitProvNode"))));

  result->Assign (Assignor::New ("InitProvHash",
    FSha1::New (
      ValueExpr::New (StrValue::New ("NULL")))));

  result->Assign (Assignor::New ("InitProvHashlist",
    FAppend::New (
      VarExpr::New ("InitProvHash"))));

  result->Assign (Assignor::New ("TempTag1",
    FConcat::New (
      VarExpr::New ("InitProvNodelist"),
      VarExpr::New ("InitProvHashlist"))));

  result->Assign (Assignor::New ("TempTag2",
    FConcat::New (
      VarExpr::New ("TempTag1"),
      VarExpr::New ("InitLhashlist"))));

  result->Assign (Assignor::New ("TempTag3",
    FConcat::New (
      VarExpr::New ("TempTag2"),
      VarExpr::New ("ProgIDlist"))));

  result->Assign (Assignor::New ("TempTag4",
    FConcat::New (
      VarExpr::New ("TempTag3"),
      VarExpr::New ("Evlist"))));

  result->Assign (Assignor::New ("Tag",
    FConcat::New (
      VarExpr::New ("TempTag4"),
      VarExpr::New ("Equilist"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("initPacketCount_attr7"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    EPACKETTEMP,
    strlist ("RLOC",
      "link_attr2",
      "initPacketCount_attr2",
      "initPacketCount_attr3",
      "initPacketCount_attr4",
      "RID",
      "R",
      "List",
      "Tag",
      "RLOC"),
    strlist ("epacketTemp_attr1",
      "epacketTemp_attr2",
      "epacketTemp_attr3",
      "epacketTemp_attr4",
      "epacketTemp_attr5",
      "epacketTemp_attr6",
      "epacketTemp_attr7",
      "epacketTemp_attr8",
      "epacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_rh2_1_eca (Ptr<Tuple> packetProv)
{
  RAPIDNET_LOG_INFO ("Prov_rh2_1_eca triggered");

  Ptr<Tuple> result = packetProv;

  result->Assign (Assignor::New ("PID2",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("packet")),
              VarExpr::New ("packetProv_attr1")),
            VarExpr::New ("packetProv_attr2")),
          VarExpr::New ("packetProv_attr3")),
        VarExpr::New ("packetProv_attr4")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID2"))));

  result->Assign (Assignor::New ("RLOC",
    VarExpr::New ("packetProv_attr1")));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rh2"))));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("R"),
        VarExpr::New ("List")))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("packetProv_attr3"),
      VarExpr::New ("packetProv_attr1"))));

  result = result->Project (
    ERECVPACKETTEMP,
    strlist ("RLOC",
      "packetProv_attr1",
      "packetProv_attr2",
      "packetProv_attr3",
      "packetProv_attr4",
      "RID",
      "R",
      "List",
      "packetProv_attr5",
      "RLOC"),
    strlist ("erecvPacketTemp_attr1",
      "erecvPacketTemp_attr2",
      "erecvPacketTemp_attr3",
      "erecvPacketTemp_attr4",
      "erecvPacketTemp_attr5",
      "erecvPacketTemp_attr6",
      "erecvPacketTemp_attr7",
      "erecvPacketTemp_attr8",
      "erecvPacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_rh2_2_eca (Ptr<Tuple> erecvPacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rh2_2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (RULEEXEC)->Join (
    erecvPacketTemp,
    strlist ("ruleExec_attr4", "ruleExec_attr3", "ruleExec_attr2", "ruleExec_attr1"),
    strlist ("erecvPacketTemp_attr8", "erecvPacketTemp_attr7", "erecvPacketTemp_attr6", "erecvPacketTemp_attr1"));

  result = AggWrapCount::New ()->Compute (result, erecvPacketTemp);

  result = result->Project (
    EPACKETCOUNT,
    strlist ("erecvPacketTemp_attr1",
      "erecvPacketTemp_attr6",
      "erecvPacketTemp_attr7",
      "erecvPacketTemp_attr8",
      "count"),
    strlist ("epacketCount_attr1",
      "epacketCount_attr2",
      "epacketCount_attr3",
      "epacketCount_attr4",
      "epacketCount_attr5"));

  SendLocal (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_rh2_4_eca (Ptr<Tuple> erecvPacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rh2_4_eca triggered");

  Ptr<Tuple> result = erecvPacketTemp;

  result->Assign (Assignor::New ("Preloc",
    FFirst::New (
      VarExpr::New ("erecvPacketTemp_attr9"))));

  result->Assign (Assignor::New ("TempTag1",
    FRemoveFirst::New (
      VarExpr::New ("erecvPacketTemp_attr9"))));

  result->Assign (Assignor::New ("PreRID",
    FFirst::New (
      VarExpr::New ("TempTag"))));

  result->Assign (Assignor::New ("TempTag2",
    FRemoveFirst::New (
      VarExpr::New ("TempTag1"))));

  result->Assign (Assignor::New ("PreLhash",
    FFirst::New (
      VarExpr::New ("TempTag2"))));

  result->Assign (Assignor::New ("TempTag3",
    FRemoveFirst::New (
      VarExpr::New ("TempTag2"))));

  result->Assign (Assignor::New ("ProgID",
    FFirst::New (
      VarExpr::New ("TempTag3"))));

  result->Assign (Assignor::New ("CurLhash",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("PreLhash"),
        VarExpr::New ("erecvPacketTemp_attr6")))));

  result = result->Project (
    PROVLINK,
    strlist ("erecvPacketTemp_attr1",
      "ProgID",
      "erecvPacketTemp_attr6",
      "CurLhash",
      "Preloc",
      "PreRID",
      "PreLhash"),
    strlist ("provLink_attr1",
      "provLink_attr2",
      "provLink_attr3",
      "provLink_attr4",
      "provLink_attr5",
      "provLink_attr6",
      "provLink_attr7"));

  Insert (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_rh2_5_eca (Ptr<Tuple> erecvPacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rh2_5_eca triggered");

  Ptr<Tuple> result = erecvPacketTemp;

  result->Assign (Assignor::New ("TempNewTag1",
    FRemoveFirst::New (
      VarExpr::New ("erecvPacketTemp_attr9"))));

  result->Assign (Assignor::New ("TempNewTag2",
    FRemoveFirst::New (
      VarExpr::New ("TempNewTag1"))));

  result->Assign (Assignor::New ("PreLhash",
    FFirst::New (
      VarExpr::New ("TempNewTag2"))));

  result->Assign (Assignor::New ("CurLhash",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("PreLhash"),
        VarExpr::New ("erecvPacketTemp_attr6")))));

  result->Assign (Assignor::New ("CurLhashlist",
    FAppend::New (
      VarExpr::New ("CurLhashlist"))));

  result->Assign (Assignor::New ("TempNewTag3",
    FRemoveFirst::New (
      VarExpr::New ("TempNewTag2"))));

  result->Assign (Assignor::New ("RIDlist",
    FAppend::New (
      VarExpr::New ("erecvPacketTemp_attr6"))));

  result->Assign (Assignor::New ("Loclist",
    FAppend::New (
      VarExpr::New ("erecvPacketTemp_attr1"))));

  result->Assign (Assignor::New ("TempNewTag4",
    FConcat::New (
      VarExpr::New ("CurLhashlist"),
      VarExpr::New ("TempNewTag3"))));

  result->Assign (Assignor::New ("TempNewTag5",
    FConcat::New (
      VarExpr::New ("RIDlist"),
      VarExpr::New ("TempNewTag4"))));

  result->Assign (Assignor::New ("NewTag",
    FConcat::New (
      VarExpr::New ("Loclist"),
      VarExpr::New ("TempNewTag5"))));

  result = result->Project (
    RECVPACKETPROV,
    strlist ("erecvPacketTemp_attr2",
      "erecvPacketTemp_attr3",
      "erecvPacketTemp_attr4",
      "erecvPacketTemp_attr5",
      "NewTag",
      "erecvPacketTemp_attr2"),
    strlist ("recvPacketProv_attr1",
      "recvPacketProv_attr2",
      "recvPacketProv_attr3",
      "recvPacketProv_attr4",
      "recvPacketProv_attr5",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDhlistLayerhsOnline::Prov_rh2_6_eca (Ptr<Tuple> recvPacketProv)
{
  RAPIDNET_LOG_INFO ("Prov_rh2_6_eca triggered");

  Ptr<Tuple> result = recvPacketProv;

  result = result->Project (
    RECVPACKET,
    strlist ("recvPacketProv_attr1",
      "recvPacketProv_attr2",
      "recvPacketProv_attr3",
      "recvPacketProv_attr4"),
    strlist ("recvPacket_attr1",
      "recvPacket_attr2",
      "recvPacket_attr3",
      "recvPacket_attr4"));

  Insert (result);
}

void
PktfwdNormDhlistLayerhsOnline::Ro1_eca (Ptr<Tuple> recvPacketProv)
{
  RAPIDNET_LOG_INFO ("Ro1_eca triggered");

  Ptr<Tuple> result = recvPacketProv;

  result->Assign (Assignor::New ("PreLoc",
    FFirst::New (
      VarExpr::New ("recvPacketProv_attr5"))));

  result->Assign (Assignor::New ("RemainTag1",
    FRemoveFirst::New (
      VarExpr::New ("recvPacketProv_attr5"))));

  result->Assign (Assignor::New ("PreRID",
    FFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("RemainTag2",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("PreLhash",
    FFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("RemainTag3",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("ProgID",
    FFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("RemainTag4",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("EvHash",
    FFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("RemainTag5",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("EqHash",
    FFirst::New (
      VarExpr::New ("RemainTag5"))));

  result->Assign (Assignor::New ("ProvID",
    FSha1::New (
      VarExpr::New ("ProgID"),
      VarExpr::New ("PIDequi"))));

  result = result->Project (
    PROVHASHTABLE,
    strlist ("recvPacketProv_attr1",
      "ProvID",
      "ProgID",
      "PreLoc",
      "PreRID",
      "PreLhash"),
    strlist ("provHashTable_attr1",
      "provHashTable_attr2",
      "provHashTable_attr3",
      "provHashTable_attr4",
      "provHashTable_attr5",
      "provHashTable_attr6"));

  Insert (result);
}

void
PktfwdNormDhlistLayerhsOnline::Ro2_eca (Ptr<Tuple> recvPacketProv)
{
  RAPIDNET_LOG_INFO ("Ro2_eca triggered");

  Ptr<Tuple> result = recvPacketProv;

  result->Assign (Assignor::New ("PID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("recvPacket")),
              VarExpr::New ("recvPacketProv_attr1")),
            VarExpr::New ("recvPacketProv_attr2")),
          VarExpr::New ("recvPacketProv_attr3")),
        VarExpr::New ("recvPacketProv_attr4")))));

  result->Assign (Assignor::New ("PreLoc",
    FFirst::New (
      VarExpr::New ("recvPacketProv_attr5"))));

  result->Assign (Assignor::New ("RemainTag1",
    FRemoveFirst::New (
      VarExpr::New ("recvPacketProv_attr5"))));

  result->Assign (Assignor::New ("PreRID",
    FFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("RemainTag2",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("PreLhash",
    FFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("RemainTag3",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("ProgID",
    FFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("RemainTag4",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("EvHash",
    FFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("RemainTag5",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("EqHash",
    FFirst::New (
      VarExpr::New ("RemainTag5"))));

  result->Assign (Assignor::New ("ProvID",
    FSha1::New (
      VarExpr::New ("ProgID"),
      VarExpr::New ("PIDequi"))));

  result = result->Project (
    RECVPACKETQRY,
    strlist ("recvPacketProv_attr1",
      "PID",
      "ProvID",
      "EvHash"),
    strlist ("recvPacketQry_attr1",
      "recvPacketQry_attr2",
      "recvPacketQry_attr3",
      "recvPacketQry_attr4"));

  Insert (result);
}

void
PktfwdNormDhlistLayerhsOnline::Rh2_eca (Ptr<Tuple> packet)
{
  RAPIDNET_LOG_INFO ("Rh2_eca triggered");

  Ptr<Tuple> result = packet;

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("packet_attr3"),
      VarExpr::New ("packet_attr1"))));

  result = result->Project (
    RECVPACKET,
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4"),
    strlist ("recvPacket_attr1",
      "recvPacket_attr2",
      "recvPacket_attr3",
      "recvPacket_attr4"));

  Insert (result);
}

void
PktfwdNormDhlistLayerhsOnline::Rho3_eca (Ptr<Tuple> packet)
{
  RAPIDNET_LOG_INFO ("Rho3_eca triggered");

  Ptr<Tuple> result = packet;

  result->Assign (Assignor::New ("PID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("recvPacket")),
              VarExpr::New ("packet_attr1")),
            VarExpr::New ("packet_attr2")),
          VarExpr::New ("packet_attr3")),
        VarExpr::New ("packet_attr4")))));

  result->Assign (Assignor::New ("PIDequi",
    FFirst::New (
      VarExpr::New ("packet_attr5"))));

  result->Assign (Assignor::New ("PIDHash1",
    FRemoveFirst::New (
      VarExpr::New ("packet_attr5"))));

  result->Assign (Assignor::New ("PIDev",
    FFirst::New (
      VarExpr::New ("PIDHash1"))));

  result->Assign (Assignor::New ("PIDHash2",
    FRemoveFirst::New (
      VarExpr::New ("PIDHash1"))));

  result->Assign (Assignor::New ("ProgID",
    FFirst::New (
      VarExpr::New ("PIDHash2"))));

  result->Assign (Assignor::New ("ProvID",
    FSha1::New (
      VarExpr::New ("ProgID"),
      VarExpr::New ("PIDequi"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("packet_attr3"),
      VarExpr::New ("packet_attr1"))));

  result = result->Project (
    RECVPACKETQRY,
    strlist ("packet_attr1",
      "PID",
      "ProvID",
      "PIDev"),
    strlist ("recvPacketQry_attr1",
      "recvPacketQry_attr2",
      "recvPacketQry_attr3",
      "recvPacketQry_attr4"));

  Insert (result);
}

