## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('myproto', ['internet-stack'])
    module.source = [
        'myproto.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'myproto'
    headers.source = [
        'myproto.h',
        'myproto-helper.h',
        ]
