/* A RapidNet application. Generated by RapidNet compiler. */

#include "pktfwd-norm-dist-hlist-online.h"
#include <cstdlib>
#include "ns3/nstime.h"
#include "ns3/simulator.h"
#include "ns3/type-ids.h"
#include "ns3/rapidnet-types.h"
#include "ns3/rapidnet-utils.h"
#include "ns3/assignor.h"
#include "ns3/selector.h"
#include "ns3/rapidnet-functions.h"

using namespace std;
using namespace ns3;
using namespace ns3::rapidnet;
using namespace ns3::rapidnet::pktfwdnormdisthlistonline;

const string PktfwdNormDistHlistOnline::EPACKETCOUNT = "epacketCount";
const string PktfwdNormDistHlistOnline::EPACKETTEMP = "epacketTemp";
const string PktfwdNormDistHlistOnline::EQUIHASHTABLE = "equiHashTable";
const string PktfwdNormDistHlistOnline::ERECVPACKETTEMP = "erecvPacketTemp";
const string PktfwdNormDistHlistOnline::FLOWENTRY = "flowEntry";
const string PktfwdNormDistHlistOnline::INITPACKET = "initPacket";
const string PktfwdNormDistHlistOnline::INITPACKETCOUNT = "initPacketCount";
const string PktfwdNormDistHlistOnline::INITPACKETHASH = "initPacketHash";
const string PktfwdNormDistHlistOnline::LINK = "link";
const string PktfwdNormDistHlistOnline::PACKET = "packet";
const string PktfwdNormDistHlistOnline::PACKETPROV = "packetProv";
const string PktfwdNormDistHlistOnline::PROGRAMID = "programID";
const string PktfwdNormDistHlistOnline::PROVHASHTABLE = "provHashTable";
const string PktfwdNormDistHlistOnline::PROVLINK = "provLink";
const string PktfwdNormDistHlistOnline::PROV_RH2_5RECVPACKETSEND = "prov_rh2_5recvPacketsend";
const string PktfwdNormDistHlistOnline::RECVPACKET = "recvPacket";
const string PktfwdNormDistHlistOnline::RECVPACKETPROV = "recvPacketProv";
const string PktfwdNormDistHlistOnline::RULEEXEC = "ruleExec";

NS_LOG_COMPONENT_DEFINE ("PktfwdNormDistHlistOnline");
NS_OBJECT_ENSURE_REGISTERED (PktfwdNormDistHlistOnline);

TypeId
PktfwdNormDistHlistOnline::GetTypeId (void)
{
  static TypeId tid = TypeId ("ns3::rapidnet::pktfwdnormdisthlistonline::PktfwdNormDistHlistOnline")
    .SetParent<RapidNetApplicationBase> ()
    .AddConstructor<PktfwdNormDistHlistOnline> ()
    ;
  return tid;
}

PktfwdNormDistHlistOnline::PktfwdNormDistHlistOnline()
{
  NS_LOG_FUNCTION_NOARGS ();
}

PktfwdNormDistHlistOnline::~PktfwdNormDistHlistOnline()
{
  NS_LOG_FUNCTION_NOARGS ();
}

void
PktfwdNormDistHlistOnline::DoDispose (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::DoDispose ();
}

void
PktfwdNormDistHlistOnline::StartApplication (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StartApplication ();
  RAPIDNET_LOG_INFO("PktfwdNormDistHlistOnline Application Started");
}

void
PktfwdNormDistHlistOnline::StopApplication ()
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StopApplication ();
  RAPIDNET_LOG_INFO("PktfwdNormDistHlistOnline Application Stopped");
}

void
PktfwdNormDistHlistOnline::InitDatabase ()
{
  //RapidNetApplicationBase::InitDatabase ();

  AddRelationWithKeys (EQUIHASHTABLE, attrdeflist (
    attrdef ("equiHashTable_attr2", IPV4)));

  AddRelationWithKeys (FLOWENTRY, attrdeflist (
    attrdef ("flowEntry_attr2", IPV4)));

  AddRelationWithKeys (INITPACKET, attrdeflist (
    attrdef ("initPacket_attr2", IPV4),
    attrdef ("initPacket_attr3", IPV4),
    attrdef ("initPacket_attr4", STR)));

  AddRelationWithKeys (LINK, attrdeflist (
    attrdef ("link_attr2", IPV4)));

  AddRelationWithKeys (PROGRAMID, attrdeflist (
    attrdef ("programID_attr2", IPV4)));

  AddRelationWithKeys (PROVHASHTABLE, attrdeflist (
    attrdef ("provHashTable_attr3", LIST)));

  AddRelationWithKeys (PROVLINK, attrdeflist ();

  AddRelationWithKeys (RECVPACKET, attrdeflist (
    attrdef ("recvPacket_attr2", IPV4),
    attrdef ("recvPacket_attr3", IPV4),
    attrdef ("recvPacket_attr4", STR)));

  AddRelationWithKeys (RECVPACKETPROV, attrdeflist (
    attrdef ("recvPacketProv_attr2", ID)));

  AddRelationWithKeys (RULEEXEC, attrdeflist (
    attrdef ("ruleExec_attr4", LIST)));

}

void
PktfwdNormDistHlistOnline::DemuxRecv (Ptr<Tuple> tuple)
{
  RapidNetApplicationBase::DemuxRecv (tuple);

  if (IsRecvEvent (tuple, PACKETPROV))
    {
      Prov_rs1_1_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPACKETTEMP))
    {
      Prov_rs1_2_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPACKETCOUNT))
    {
      Prov_rs1_3_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPACKETTEMP))
    {
      Prov_rs1_4_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPACKETTEMP))
    {
      Prov_rs1_5_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKET))
    {
      Rs1_eca (tuple);
    }
  if (IsInsertEvent (tuple, INITPACKET))
    {
      Prov_ri1Eca0Ins (tuple);
    }
  if (IsInsertEvent (tuple, PROGRAMID))
    {
      Prov_ri1Eca1Ins (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETHASH))
    {
      Prov_ri2_eca (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETCOUNT))
    {
      Prov_ri3_eca (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETCOUNT))
    {
      Rh1_eca (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETCOUNT))
    {
      Prov_rh1_1_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKETPROV))
    {
      Prov_rh2_1_eca (tuple);
    }
  if (IsRecvEvent (tuple, ERECVPACKETTEMP))
    {
      Prov_rh2_2_eca (tuple);
    }
  if (IsRecvEvent (tuple, ERECVPACKETTEMP))
    {
      Prov_rh2_4_eca (tuple);
    }
  if (IsRecvEvent (tuple, PROV_RH2_5RECVPACKETSEND))
    {
      Prov_rh2_5ECAMat (tuple);
    }
  if (IsRecvEvent (tuple, ERECVPACKETTEMP))
    {
      Prov_rh2_5_eca (tuple);
    }
  if (IsInsertEvent (tuple, RECVPACKET))
    {
      Ro1Eca0Ins (tuple);
    }
  if (IsDeleteEvent (tuple, RECVPACKET))
    {
      Ro1Eca0Del (tuple);
    }
  if (IsInsertEvent (tuple, RECVPACKET))
    {
      Ro2Eca0Ins (tuple);
    }
  if (IsDeleteEvent (tuple, RECVPACKET))
    {
      Ro2Eca0Del (tuple);
    }
  if (IsRecvEvent (tuple, PACKET))
    {
      Rh2_eca (tuple);
    }
  if (IsInsertEvent (tuple, RECVPACKET))
    {
      Rh2Eca0Ins (tuple);
    }
  if (IsDeleteEvent (tuple, RECVPACKET))
    {
      Rh2Eca0Del (tuple);
    }
}

void
PktfwdNormDistHlistOnline::Prov_rs1_1_eca (Ptr<Tuple> packetProv)
{
  RAPIDNET_LOG_INFO ("Prov_rs1_1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (FLOWENTRY)->Join (
    packetProv,
    strlist ("flowEntry_attr2", "flowEntry_attr1"),
    strlist ("packetProv_attr3", "packetProv_attr1"));

  result = GetRelation (LINK)->Join (
    result,
    strlist ("link_attr2", "link_attr1"),
    strlist ("flowEntry_attr3", "packetProv_attr1"));

  result->Assign (Assignor::New ("PID3",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            ValueExpr::New (StrValue::New ("flowEntry")),
            VarExpr::New ("packetProv_attr1")),
          VarExpr::New ("packetProv_attr3")),
        VarExpr::New ("flowEntry_attr3")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID3"))));

  result->Assign (Assignor::New ("PID4",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("link")),
          VarExpr::New ("packetProv_attr1")),
        VarExpr::New ("flowEntry_attr3")))));

  result->Assign (Assignor::New ("List4",
    FAppend::New (
      VarExpr::New ("PID4"))));

  result->Assign (Assignor::New ("List",
    FConcat::New (
      VarExpr::New ("List"),
      VarExpr::New ("List4"))));

  result->Assign (Assignor::New ("RLOC",
    VarExpr::New ("packetProv_attr1")));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rs1"))));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          VarExpr::New ("R"),
          VarExpr::New ("RLOC")),
        VarExpr::New ("List")))));

  result = result->Project (
    EPACKETTEMP,
    strlist ("RLOC",
      "flowEntry_attr3",
      "packetProv_attr2",
      "packetProv_attr3",
      "packetProv_attr4",
      "RID",
      "R",
      "List",
      "packetProv_attr5",
      "RLOC"),
    strlist ("epacketTemp_attr1",
      "epacketTemp_attr2",
      "epacketTemp_attr3",
      "epacketTemp_attr4",
      "epacketTemp_attr5",
      "epacketTemp_attr6",
      "epacketTemp_attr7",
      "epacketTemp_attr8",
      "epacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDistHlistOnline::Prov_rs1_2_eca (Ptr<Tuple> epacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rs1_2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (RULEEXEC)->Join (
    epacketTemp,
    strlist ("ruleExec_attr4", "ruleExec_attr3", "ruleExec_attr2", "ruleExec_attr1"),
    strlist ("epacketTemp_attr8", "epacketTemp_attr7", "epacketTemp_attr6", "epacketTemp_attr1"));

  result = AggWrapCount::New ()->Compute (result, epacketTemp);

  result = result->Project (
    EPACKETCOUNT,
    strlist ("epacketTemp_attr1",
      "epacketTemp_attr6",
      "epacketTemp_attr7",
      "epacketTemp_attr8",
      "count"),
    strlist ("epacketCount_attr1",
      "epacketCount_attr2",
      "epacketCount_attr3",
      "epacketCount_attr4",
      "epacketCount_attr5"));

  SendLocal (result);
}

void
PktfwdNormDistHlistOnline::Prov_rs1_3_eca (Ptr<Tuple> epacketCount)
{
  RAPIDNET_LOG_INFO ("Prov_rs1_3_eca triggered");

  Ptr<Tuple> result = epacketCount;

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("epacketCount_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    RULEEXEC,
    strlist ("epacketCount_attr1",
      "epacketCount_attr2",
      "epacketCount_attr3",
      "epacketCount_attr4"),
    strlist ("ruleExec_attr1",
      "ruleExec_attr2",
      "ruleExec_attr3",
      "ruleExec_attr4"));

  Insert (result);
}

void
PktfwdNormDistHlistOnline::Prov_rs1_4_eca (Ptr<Tuple> epacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rs1_4_eca triggered");

  Ptr<Tuple> result = epacketTemp;

  result->Assign (Assignor::New ("PreCount",
    FFirst::New (
      VarExpr::New ("epacketTemp_attr9"))));

  result->Assign (Assignor::New ("CurCount",
    Operation::New (RN_PLUS,
      VarExpr::New ("PreCount"),
      ValueExpr::New (Int32Value::New (1)))));

  result->Assign (Assignor::New ("TempTag1",
    FRemoveFirst::New (
      VarExpr::New ("epacketTemp_attr9"))));

  result->Assign (Assignor::New ("Preloc",
    FFirst::New (
      VarExpr::New ("TempTag"))));

  result->Assign (Assignor::New ("TempTag2",
    FRemoveFirst::New (
      VarExpr::New ("TempTag1"))));

  result->Assign (Assignor::New ("PreRID",
    FFirst::New (
      VarExpr::New ("TempTag2"))));

  result = result->Project (
    PROVLINK,
    strlist ("epacketTemp_attr1",
      "epacketTemp_attr6",
      "CurCount",
      "Preloc",
      "PreRID",
      "PreCount"),
    strlist ("provLink_attr1",
      "provLink_attr2",
      "provLink_attr3",
      "provLink_attr4",
      "provLink_attr5",
      "provLink_attr6"));

  Insert (result);
}

void
PktfwdNormDistHlistOnline::Prov_rs1_5_eca (Ptr<Tuple> epacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rs1_5_eca triggered");

  Ptr<Tuple> result = epacketTemp;

  result->Assign (Assignor::New ("Count",
    FFirst::New (
      VarExpr::New ("epacketTemp_attr9"))));

  result->Assign (Assignor::New ("NewCount",
    Operation::New (RN_PLUS,
      VarExpr::New ("Count"),
      ValueExpr::New (Int32Value::New (1)))));

  result->Assign (Assignor::New ("NewCountlist",
    FAppend::New (
      VarExpr::New ("NewCount"))));

  result->Assign (Assignor::New ("TempNewTag1",
    FRemoveFirst::New (
      VarExpr::New ("epacketTemp_attr9"))));

  result->Assign (Assignor::New ("TempNewTag2",
    FRemoveFirst::New (
      VarExpr::New ("TempNewTag1"))));

  result->Assign (Assignor::New ("TempNewTag3",
    FRemoveFirst::New (
      VarExpr::New ("TempNewTag2"))));

  result->Assign (Assignor::New ("RIDlist",
    FAppend::New (
      VarExpr::New ("epacketTemp_attr6"))));

  result->Assign (Assignor::New ("Loclist",
    FAppend::New (
      VarExpr::New ("epacketTemp_attr1"))));

  result->Assign (Assignor::New ("TempNewTag4",
    FConcat::New (
      VarExpr::New ("RIDlist"),
      VarExpr::New ("TempNewTag3"))));

  result->Assign (Assignor::New ("TempNewTag5",
    FConcat::New (
      VarExpr::New ("Loclist"),
      VarExpr::New ("TempNewTag4"))));

  result->Assign (Assignor::New ("NewTag",
    FConcat::New (
      VarExpr::New ("NewCountlist"),
      VarExpr::New ("TempNewTag5"))));

  result = result->Project (
    PACKETPROV,
    strlist ("epacketTemp_attr2",
      "epacketTemp_attr3",
      "epacketTemp_attr4",
      "epacketTemp_attr5",
      "NewTag",
      "epacketTemp_attr2"),
    strlist ("packetProv_attr1",
      "packetProv_attr2",
      "packetProv_attr3",
      "packetProv_attr4",
      "packetProv_attr5",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDistHlistOnline::Rs1_eca (Ptr<Tuple> packet)
{
  RAPIDNET_LOG_INFO ("Rs1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (FLOWENTRY)->Join (
    packet,
    strlist ("flowEntry_attr2", "flowEntry_attr1"),
    strlist ("packet_attr3", "packet_attr1"));

  result = GetRelation (LINK)->Join (
    result,
    strlist ("link_attr2", "link_attr1"),
    strlist ("flowEntry_attr3", "packet_attr1"));

  result = result->Project (
    PACKET,
    strlist ("flowEntry_attr3",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "packet_attr5",
      "flowEntry_attr3"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "packet_attr5",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDistHlistOnline::Prov_ri1Eca0Ins (Ptr<Tuple> initPacket)
{
  RAPIDNET_LOG_INFO ("Prov_ri1Eca0Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (PROGRAMID)->Join (
    initPacket,
    strlist ("programID_attr2", "programID_attr1"),
    strlist ("initPacket_attr3", "initPacket_attr1"));

  result->Assign (Assignor::New ("PIDequi",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("")),
          VarExpr::New ("initPacket_attr1")),
        VarExpr::New ("initPacket_attr3")))));

  result = result->Project (
    INITPACKETHASH,
    strlist ("initPacket_attr1",
      "initPacket_attr2",
      "initPacket_attr3",
      "initPacket_attr4",
      "PIDequi",
      "programID_attr3"),
    strlist ("initPacketHash_attr1",
      "initPacketHash_attr2",
      "initPacketHash_attr3",
      "initPacketHash_attr4",
      "initPacketHash_attr5",
      "initPacketHash_attr6"));

  SendLocal (result);
}

void
PktfwdNormDistHlistOnline::Prov_ri1Eca1Ins (Ptr<Tuple> programID)
{
  RAPIDNET_LOG_INFO ("Prov_ri1Eca1Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (INITPACKET)->Join (
    programID,
    strlist ("initPacket_attr3", "initPacket_attr1"),
    strlist ("programID_attr2", "programID_attr1"));

  result->Assign (Assignor::New ("PIDequi",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("")),
          VarExpr::New ("programID_attr1")),
        VarExpr::New ("programID_attr2")))));

  result = result->Project (
    INITPACKETHASH,
    strlist ("programID_attr1",
      "initPacket_attr2",
      "programID_attr2",
      "initPacket_attr4",
      "PIDequi",
      "programID_attr3"),
    strlist ("initPacketHash_attr1",
      "initPacketHash_attr2",
      "initPacketHash_attr3",
      "initPacketHash_attr4",
      "initPacketHash_attr5",
      "initPacketHash_attr6"));

  SendLocal (result);
}

void
PktfwdNormDistHlistOnline::Prov_ri2_eca (Ptr<Tuple> initPacketHash)
{
  RAPIDNET_LOG_INFO ("Prov_ri2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (EQUIHASHTABLE)->Join (
    initPacketHash,
    strlist ("equiHashTable_attr2", "equiHashTable_attr1", "equiHashTable_attr3"),
    strlist ("initPacketHash_attr3", "initPacketHash_attr1", "initPacketHash_attr5"));

  result = AggWrapCount::New ()->Compute (result, initPacketHash);

  result = result->Project (
    INITPACKETCOUNT,
    strlist ("initPacketHash_attr1",
      "initPacketHash_attr2",
      "initPacketHash_attr3",
      "initPacketHash_attr4",
      "initPacketHash_attr5",
      "initPacketHash_attr6",
      "count"),
    strlist ("initPacketCount_attr1",
      "initPacketCount_attr2",
      "initPacketCount_attr3",
      "initPacketCount_attr4",
      "initPacketCount_attr5",
      "initPacketCount_attr6",
      "initPacketCount_attr7"));

  SendLocal (result);
}

void
PktfwdNormDistHlistOnline::Prov_ri3_eca (Ptr<Tuple> initPacketCount)
{
  RAPIDNET_LOG_INFO ("Prov_ri3_eca triggered");

  Ptr<Tuple> result = initPacketCount;

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("initPacketCount_attr7"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    EQUIHASHTABLE,
    strlist ("initPacketCount_attr1",
      "initPacketCount_attr3",
      "initPacketCount_attr5"),
    strlist ("equiHashTable_attr1",
      "equiHashTable_attr2",
      "equiHashTable_attr3"));

  Insert (result);
}

void
PktfwdNormDistHlistOnline::Rh1_eca (Ptr<Tuple> initPacketCount)
{
  RAPIDNET_LOG_INFO ("Rh1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (LINK)->Join (
    initPacketCount,
    strlist ("link_attr1"),
    strlist ("initPacketCount_attr1"));

  result->Assign (Assignor::New ("PIDev",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("initPacket")),
              VarExpr::New ("initPacketCount_attr1")),
            VarExpr::New ("initPacketCount_attr2")),
          VarExpr::New ("initPacketCount_attr3")),
        VarExpr::New ("initPacketCount_attr4")))));

  result->Assign (Assignor::New ("PIDequiHash",
    FAppend::New (
      VarExpr::New ("initPacketCount_attr5"))));

  result->Assign (Assignor::New ("PIDevHash",
    FAppend::New (
      VarExpr::New ("PIDev"))));

  result->Assign (Assignor::New ("ProgIDlist",
    FAppend::New (
      VarExpr::New ("initPacketCount_attr6"))));

  result->Assign (Assignor::New ("PIDHash1",
    FConcat::New (
      VarExpr::New ("PIDequiHash"),
      VarExpr::New ("PIDevHash"))));

  result->Assign (Assignor::New ("PIDHash",
    FConcat::New (
      VarExpr::New ("PIDHash1"),
      VarExpr::New ("ProgIDlist"))));

  result = result->Select (Selector::New (
    Operation::New (RN_NEQ,
      VarExpr::New ("initPacketCount_attr7"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    PACKET,
    strlist ("link_attr2",
      "initPacketCount_attr2",
      "initPacketCount_attr3",
      "initPacketCount_attr4",
      "PIDHash",
      "link_attr2"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "packet_attr5",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDistHlistOnline::Prov_rh1_1_eca (Ptr<Tuple> initPacketCount)
{
  RAPIDNET_LOG_INFO ("Prov_rh1_1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (LINK)->Join (
    initPacketCount,
    strlist ("link_attr1"),
    strlist ("initPacketCount_attr1"));

  result->Assign (Assignor::New ("PID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("link")),
          VarExpr::New ("initPacketCount_attr1")),
        VarExpr::New ("link_attr2")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID"))));

  result->Assign (Assignor::New ("RLOC",
    VarExpr::New ("initPacketCount_attr1")));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          VarExpr::New ("R"),
          VarExpr::New ("RLOC")),
        VarExpr::New ("List")))));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rh1"))));

  result->Assign (Assignor::New ("Equilist",
    FAppend::New (
      VarExpr::New ("initPacketCount_attr5"))));

  result->Assign (Assignor::New ("PIDev",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("initPacket")),
              VarExpr::New ("initPacketCount_attr1")),
            VarExpr::New ("initPacketCount_attr2")),
          VarExpr::New ("initPacketCount_attr3")),
        VarExpr::New ("initPacketCount_attr4")))));

  result->Assign (Assignor::New ("Evlist",
    FAppend::New (
      VarExpr::New ("PIDev"))));

  result->Assign (Assignor::New ("ProgIDlist",
    FAppend::New (
      VarExpr::New ("initPacketCount_attr6"))));

  result->Assign (Assignor::New ("Count",
    ValueExpr::New (Int32Value::New (0))));

  result->Assign (Assignor::New ("Countlist",
    FAppend::New (
      VarExpr::New ("Count"))));

  result->Assign (Assignor::New ("InitProvNode",
    VarExpr::New ("RLOC")));

  result->Assign (Assignor::New ("InitProvNodelist",
    FAppend::New (
      VarExpr::New ("InitProvNode"))));

  result->Assign (Assignor::New ("InitProvHash",
    FSha1::New (
      ValueExpr::New (StrValue::New ("NULL")))));

  result->Assign (Assignor::New ("InitProvHashlist",
    FAppend::New (
      VarExpr::New ("InitProvHash"))));

  result->Assign (Assignor::New ("TempTag1",
    FConcat::New (
      VarExpr::New ("Countlist"),
      VarExpr::New ("InitProvNodelist"))));

  result->Assign (Assignor::New ("TempTag2",
    FConcat::New (
      VarExpr::New ("TempTag1"),
      VarExpr::New ("InitProvHashlist"))));

  result->Assign (Assignor::New ("TempTag3",
    FConcat::New (
      VarExpr::New ("TempTag2"),
      VarExpr::New ("Equilist"))));

  result->Assign (Assignor::New ("TempTag4",
    FConcat::New (
      VarExpr::New ("TempTag3"),
      VarExpr::New ("Evlist"))));

  result->Assign (Assignor::New ("Tag",
    FConcat::New (
      VarExpr::New ("TempTag4"),
      VarExpr::New ("ProgIDlist"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("initPacketCount_attr7"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    EPACKETTEMP,
    strlist ("RLOC",
      "link_attr2",
      "initPacketCount_attr2",
      "initPacketCount_attr3",
      "initPacketCount_attr4",
      "RID",
      "R",
      "List",
      "Tag",
      "RLOC"),
    strlist ("epacketTemp_attr1",
      "epacketTemp_attr2",
      "epacketTemp_attr3",
      "epacketTemp_attr4",
      "epacketTemp_attr5",
      "epacketTemp_attr6",
      "epacketTemp_attr7",
      "epacketTemp_attr8",
      "epacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDistHlistOnline::Prov_rh2_1_eca (Ptr<Tuple> packetProv)
{
  RAPIDNET_LOG_INFO ("Prov_rh2_1_eca triggered");

  Ptr<Tuple> result = packetProv;

  result->Assign (Assignor::New ("PID2",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("packet")),
              VarExpr::New ("packetProv_attr1")),
            VarExpr::New ("packetProv_attr2")),
          VarExpr::New ("packetProv_attr3")),
        VarExpr::New ("packetProv_attr4")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID2"))));

  result->Assign (Assignor::New ("RLOC",
    VarExpr::New ("packetProv_attr1")));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rh2"))));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          VarExpr::New ("R"),
          VarExpr::New ("RLOC")),
        VarExpr::New ("List")))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("packetProv_attr3"),
      VarExpr::New ("packetProv_attr1"))));

  result = result->Project (
    ERECVPACKETTEMP,
    strlist ("RLOC",
      "packetProv_attr1",
      "packetProv_attr2",
      "packetProv_attr3",
      "packetProv_attr4",
      "RID",
      "R",
      "List",
      "packetProv_attr5",
      "RLOC"),
    strlist ("erecvPacketTemp_attr1",
      "erecvPacketTemp_attr2",
      "erecvPacketTemp_attr3",
      "erecvPacketTemp_attr4",
      "erecvPacketTemp_attr5",
      "erecvPacketTemp_attr6",
      "erecvPacketTemp_attr7",
      "erecvPacketTemp_attr8",
      "erecvPacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDistHlistOnline::Prov_rh2_2_eca (Ptr<Tuple> erecvPacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rh2_2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (RULEEXEC)->Join (
    erecvPacketTemp,
    strlist ("ruleExec_attr4", "ruleExec_attr3", "ruleExec_attr2", "ruleExec_attr1"),
    strlist ("erecvPacketTemp_attr8", "erecvPacketTemp_attr7", "erecvPacketTemp_attr6", "erecvPacketTemp_attr1"));

  result = AggWrapCount::New ()->Compute (result, erecvPacketTemp);

  result = result->Project (
    EPACKETCOUNT,
    strlist ("erecvPacketTemp_attr1",
      "erecvPacketTemp_attr6",
      "erecvPacketTemp_attr7",
      "erecvPacketTemp_attr8",
      "count"),
    strlist ("epacketCount_attr1",
      "epacketCount_attr2",
      "epacketCount_attr3",
      "epacketCount_attr4",
      "epacketCount_attr5"));

  SendLocal (result);
}

void
PktfwdNormDistHlistOnline::Prov_rh2_4_eca (Ptr<Tuple> erecvPacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rh2_4_eca triggered");

  Ptr<Tuple> result = erecvPacketTemp;

  result->Assign (Assignor::New ("PreCount",
    FFirst::New (
      VarExpr::New ("erecvPacketTemp_attr9"))));

  result->Assign (Assignor::New ("CurCount",
    Operation::New (RN_PLUS,
      VarExpr::New ("PreCount"),
      ValueExpr::New (Int32Value::New (1)))));

  result->Assign (Assignor::New ("TempTag1",
    FRemoveFirst::New (
      VarExpr::New ("erecvPacketTemp_attr9"))));

  result->Assign (Assignor::New ("Preloc",
    FFirst::New (
      VarExpr::New ("TempTag"))));

  result->Assign (Assignor::New ("TempTag2",
    FRemoveFirst::New (
      VarExpr::New ("TempTag1"))));

  result->Assign (Assignor::New ("PreRID",
    FFirst::New (
      VarExpr::New ("TempTag2"))));

  result = result->Project (
    PROVLINK,
    strlist ("erecvPacketTemp_attr1",
      "erecvPacketTemp_attr6",
      "CurCount",
      "Preloc",
      "PreRID",
      "PreCount"),
    strlist ("provLink_attr1",
      "provLink_attr2",
      "provLink_attr3",
      "provLink_attr4",
      "provLink_attr5",
      "provLink_attr6"));

  Insert (result);
}

void
PktfwdNormDistHlistOnline::Prov_rh2_5ECAMat (Ptr<Tuple> prov_rh2_5recvPacketsend)
{
  RAPIDNET_LOG_INFO ("Prov_rh2_5ECAMat triggered");

  Ptr<Tuple> result = prov_rh2_5recvPacketsend;

  result = result->Project (
    RECVPACKET,
    strlist ("prov_rh2_5recvPacketsend_attr1",
      "prov_rh2_5recvPacketsend_attr2",
      "prov_rh2_5recvPacketsend_attr3",
      "prov_rh2_5recvPacketsend_attr4",
      "prov_rh2_5recvPacketsend_attr5"),
    strlist ("recvPacket_attr1",
      "recvPacket_attr2",
      "recvPacket_attr3",
      "recvPacket_attr4",
      "recvPacket_attr5"));

  Insert (result);
}

void
PktfwdNormDistHlistOnline::Prov_rh2_5_eca (Ptr<Tuple> erecvPacketTemp)
{
  RAPIDNET_LOG_INFO ("Prov_rh2_5_eca triggered");

  Ptr<Tuple> result = erecvPacketTemp;

  result->Assign (Assignor::New ("Count",
    FFirst::New (
      VarExpr::New ("erecvPacketTemp_attr9"))));

  result->Assign (Assignor::New ("NewCount",
    Operation::New (RN_PLUS,
      VarExpr::New ("Count"),
      ValueExpr::New (Int32Value::New (1)))));

  result->Assign (Assignor::New ("NewCountlist",
    FAppend::New (
      VarExpr::New ("NewCount"))));

  result->Assign (Assignor::New ("TempNewTag1",
    FRemoveFirst::New (
      VarExpr::New ("erecvPacketTemp_attr9"))));

  result->Assign (Assignor::New ("TempNewTag2",
    FRemoveFirst::New (
      VarExpr::New ("TempNewTag1"))));

  result->Assign (Assignor::New ("TempNewTag3",
    FRemoveFirst::New (
      VarExpr::New ("TempNewTag2"))));

  result->Assign (Assignor::New ("RIDlist",
    FAppend::New (
      VarExpr::New ("erecvPacketTemp_attr6"))));

  result->Assign (Assignor::New ("Loclist",
    FAppend::New (
      VarExpr::New ("erecvPacketTemp_attr1"))));

  result->Assign (Assignor::New ("TempNewTag4",
    FConcat::New (
      VarExpr::New ("RIDlist"),
      VarExpr::New ("TempNewTag3"))));

  result->Assign (Assignor::New ("TempNewTag5",
    FConcat::New (
      VarExpr::New ("Loclist"),
      VarExpr::New ("TempNewTag4"))));

  result->Assign (Assignor::New ("NewTag",
    FConcat::New (
      VarExpr::New ("NewCountlist"),
      VarExpr::New ("TempNewTag5"))));

  result = result->Project (
    PROV_RH2_5RECVPACKETSEND,
    strlist ("erecvPacketTemp_attr2",
      "erecvPacketTemp_attr3",
      "erecvPacketTemp_attr4",
      "erecvPacketTemp_attr5",
      "NewTag",
      "erecvPacketTemp_attr2"),
    strlist ("prov_rh2_5recvPacketsend_attr1",
      "prov_rh2_5recvPacketsend_attr2",
      "prov_rh2_5recvPacketsend_attr3",
      "prov_rh2_5recvPacketsend_attr4",
      "prov_rh2_5recvPacketsend_attr5",
      RN_DEST));

  Send (result);
}

void
PktfwdNormDistHlistOnline::Ro1Eca0Ins (Ptr<Tuple> recvPacket)
{
  RAPIDNET_LOG_INFO ("Ro1Eca0Ins triggered");

  Ptr<Tuple> result = recvPacket;

  result->Assign (Assignor::New ("Count",
    FFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("RemainTag1",
    FRemoveFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("Loc",
    FFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("RemainTag2",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("RID",
    FFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("RemainTag3",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("PIDequi",
    FFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("RemainTag4",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("PIDev",
    FFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("RemainTag5",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("ProgID",
    FFirst::New (
      VarExpr::New ("RemainTag5"))));

  result->Assign (Assignor::New ("EquiHash",
    FSha1::New (
      VarExpr::New ("ProgID"),
      VarExpr::New ("PIDequi"))));

  result = result->Project (
    PROVHASHTABLE,
    strlist ("recvPacket_attr1",
      "EquiHash",
      "ProgID",
      "Loc",
      "RID",
      "Count"),
    strlist ("provHashTable_attr1",
      "provHashTable_attr2",
      "provHashTable_attr3",
      "provHashTable_attr4",
      "provHashTable_attr5",
      "provHashTable_attr6"));

  Insert (result);
}

void
PktfwdNormDistHlistOnline::Ro1Eca0Del (Ptr<Tuple> recvPacket)
{
  RAPIDNET_LOG_INFO ("Ro1Eca0Del triggered");

  Ptr<Tuple> result = recvPacket;

  result->Assign (Assignor::New ("Count",
    FFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("RemainTag1",
    FRemoveFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("Loc",
    FFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("RemainTag2",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("RID",
    FFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("RemainTag3",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("PIDequi",
    FFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("RemainTag4",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("PIDev",
    FFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("RemainTag5",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("ProgID",
    FFirst::New (
      VarExpr::New ("RemainTag5"))));

  result->Assign (Assignor::New ("EquiHash",
    FSha1::New (
      VarExpr::New ("ProgID"),
      VarExpr::New ("PIDequi"))));

  result = result->Project (
    PROVHASHTABLE,
    strlist ("recvPacket_attr1",
      "EquiHash",
      "ProgID",
      "Loc",
      "RID",
      "Count"),
    strlist ("provHashTable_attr1",
      "provHashTable_attr2",
      "provHashTable_attr3",
      "provHashTable_attr4",
      "provHashTable_attr5",
      "provHashTable_attr6"));

  Delete (result);
}

void
PktfwdNormDistHlistOnline::Ro2Eca0Ins (Ptr<Tuple> recvPacket)
{
  RAPIDNET_LOG_INFO ("Ro2Eca0Ins triggered");

  Ptr<Tuple> result = recvPacket;

  result->Assign (Assignor::New ("PID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("recvPacket")),
              VarExpr::New ("recvPacket_attr1")),
            VarExpr::New ("recvPacket_attr2")),
          VarExpr::New ("recvPacket_attr3")),
        VarExpr::New ("recvPacket_attr4")))));

  result->Assign (Assignor::New ("Count",
    FFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("RemainTag1",
    FRemoveFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("Loc",
    FFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("RemainTag2",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("RID",
    FFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("RemainTag3",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("PIDequi",
    FFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("RemainTag4",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("PIDev",
    FFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("RemainTag5",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("ProgID",
    FFirst::New (
      VarExpr::New ("RemainTag5"))));

  result->Assign (Assignor::New ("EquiHash",
    FSha1::New (
      VarExpr::New ("ProgID"),
      VarExpr::New ("PIDequi"))));

  result = result->Project (
    RECVPACKETPROV,
    strlist ("recvPacket_attr1",
      "PID",
      "EquiHash",
      "PIDev"),
    strlist ("recvPacketProv_attr1",
      "recvPacketProv_attr2",
      "recvPacketProv_attr3",
      "recvPacketProv_attr4"));

  Insert (result);
}

void
PktfwdNormDistHlistOnline::Ro2Eca0Del (Ptr<Tuple> recvPacket)
{
  RAPIDNET_LOG_INFO ("Ro2Eca0Del triggered");

  Ptr<Tuple> result = recvPacket;

  result->Assign (Assignor::New ("PID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("recvPacket")),
              VarExpr::New ("recvPacket_attr1")),
            VarExpr::New ("recvPacket_attr2")),
          VarExpr::New ("recvPacket_attr3")),
        VarExpr::New ("recvPacket_attr4")))));

  result->Assign (Assignor::New ("Count",
    FFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("RemainTag1",
    FRemoveFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("Loc",
    FFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("RemainTag2",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag1"))));

  result->Assign (Assignor::New ("RID",
    FFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("RemainTag3",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag2"))));

  result->Assign (Assignor::New ("PIDequi",
    FFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("RemainTag4",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag3"))));

  result->Assign (Assignor::New ("PIDev",
    FFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("RemainTag5",
    FRemoveFirst::New (
      VarExpr::New ("RemainTag4"))));

  result->Assign (Assignor::New ("ProgID",
    FFirst::New (
      VarExpr::New ("RemainTag5"))));

  result->Assign (Assignor::New ("EquiHash",
    FSha1::New (
      VarExpr::New ("ProgID"),
      VarExpr::New ("PIDequi"))));

  result = result->Project (
    RECVPACKETPROV,
    strlist ("recvPacket_attr1",
      "PID",
      "EquiHash",
      "PIDev"),
    strlist ("recvPacketProv_attr1",
      "recvPacketProv_attr2",
      "recvPacketProv_attr3",
      "recvPacketProv_attr4"));

  Delete (result);
}

void
PktfwdNormDistHlistOnline::Rh2_eca (Ptr<Tuple> packet)
{
  RAPIDNET_LOG_INFO ("Rh2_eca triggered");

  Ptr<Tuple> result = packet;

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("packet_attr3"),
      VarExpr::New ("packet_attr1"))));

  result = result->Project (
    RECVPACKET,
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "packet_attr5"),
    strlist ("recvPacket_attr1",
      "recvPacket_attr2",
      "recvPacket_attr3",
      "recvPacket_attr4",
      "recvPacket_attr5"));

  Insert (result);
}

void
PktfwdNormDistHlistOnline::Rh2Eca0Ins (Ptr<Tuple> recvPacket)
{
  RAPIDNET_LOG_INFO ("Rh2Eca0Ins triggered");

  Ptr<Tuple> result = recvPacket;

  result->Assign (Assignor::New ("PID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("recvPacket")),
              VarExpr::New ("recvPacket_attr1")),
            VarExpr::New ("recvPacket_attr2")),
          VarExpr::New ("recvPacket_attr3")),
        VarExpr::New ("recvPacket_attr4")))));

  result->Assign (Assignor::New ("PIDequi",
    FFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("PIDHash1",
    FRemoveFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("PIDev",
    FFirst::New (
      VarExpr::New ("PIDHash1"))));

  result->Assign (Assignor::New ("PIDHash2",
    FRemoveFirst::New (
      VarExpr::New ("PIDHash1"))));

  result->Assign (Assignor::New ("ProgID",
    FFirst::New (
      VarExpr::New ("PIDHash2"))));

  result->Assign (Assignor::New ("EquiHash",
    FSha1::New (
      VarExpr::New ("ProgID"),
      VarExpr::New ("PIDequi"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("recvPacket_attr3"),
      VarExpr::New ("recvPacket_attr1"))));

  result = result->Project (
    RECVPACKETPROV,
    strlist ("recvPacket_attr1",
      "PID",
      "EquiHash",
      "PIDev"),
    strlist ("recvPacketProv_attr1",
      "recvPacketProv_attr2",
      "recvPacketProv_attr3",
      "recvPacketProv_attr4"));

  Insert (result);
}

void
PktfwdNormDistHlistOnline::Rh2Eca0Del (Ptr<Tuple> recvPacket)
{
  RAPIDNET_LOG_INFO ("Rh2Eca0Del triggered");

  Ptr<Tuple> result = recvPacket;

  result->Assign (Assignor::New ("PID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("recvPacket")),
              VarExpr::New ("recvPacket_attr1")),
            VarExpr::New ("recvPacket_attr2")),
          VarExpr::New ("recvPacket_attr3")),
        VarExpr::New ("recvPacket_attr4")))));

  result->Assign (Assignor::New ("PIDequi",
    FFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("PIDHash1",
    FRemoveFirst::New (
      VarExpr::New ("recvPacket_attr5"))));

  result->Assign (Assignor::New ("PIDev",
    FFirst::New (
      VarExpr::New ("PIDHash1"))));

  result->Assign (Assignor::New ("PIDHash2",
    FRemoveFirst::New (
      VarExpr::New ("PIDHash1"))));

  result->Assign (Assignor::New ("ProgID",
    FFirst::New (
      VarExpr::New ("PIDHash2"))));

  result->Assign (Assignor::New ("EquiHash",
    FSha1::New (
      VarExpr::New ("ProgID"),
      VarExpr::New ("PIDequi"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("recvPacket_attr3"),
      VarExpr::New ("recvPacket_attr1"))));

  result = result->Project (
    RECVPACKETPROV,
    strlist ("recvPacket_attr1",
      "PID",
      "EquiHash",
      "PIDev"),
    strlist ("recvPacketProv_attr1",
      "recvPacketProv_attr2",
      "recvPacketProv_attr3",
      "recvPacketProv_attr4"));

  Delete (result);
}

