## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('dns-prov-comp-strawman', ['internet-stack'])
    module.source = [
        'dns-prov-comp-strawman.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'dns-prov-comp-strawman'
    headers.source = [
        'dns-prov-comp-strawman.h',
        'dns-prov-comp-strawman-helper.h',
        ]
