/* A RapidNet application. Generated by RapidNet compiler. */

#include "pktfwd-sdn-prov-comp-static-check.h"
#include <cstdlib>
#include "ns3/nstime.h"
#include "ns3/simulator.h"
#include "ns3/type-ids.h"
#include "ns3/rapidnet-types.h"
#include "ns3/rapidnet-utils.h"
#include "ns3/assignor.h"
#include "ns3/selector.h"
#include "ns3/rapidnet-functions.h"

using namespace std;
using namespace ns3;
using namespace ns3::rapidnet;
using namespace ns3::rapidnet::pktfwdsdnprovcompstaticcheck;

const string PktfwdSdnProvCompStaticCheck::DEVICE = "device";
const string PktfwdSdnProvCompStaticCheck::EMATCHINGPACKET = "eMatchingPacket";
const string PktfwdSdnProvCompStaticCheck::EMATCHINGPACKETCOUNT = "eMatchingPacketCount";
const string PktfwdSdnProvCompStaticCheck::EMATCHINGPACKETTEMP = "eMatchingPacketTemp";
const string PktfwdSdnProvCompStaticCheck::EPACKET = "ePacket";
const string PktfwdSdnProvCompStaticCheck::EPACKETTEMP = "ePacketTemp";
const string PktfwdSdnProvCompStaticCheck::EPAKETCOUNT = "ePaketCount";
const string PktfwdSdnProvCompStaticCheck::ERECVPACKET = "eRecvPacket";
const string PktfwdSdnProvCompStaticCheck::ERECVPACKETCOUNT = "eRecvPacketCount";
const string PktfwdSdnProvCompStaticCheck::ERECVPACKETTEMP = "eRecvPacketTemp";
const string PktfwdSdnProvCompStaticCheck::EQUIHASHTABLE = "equiHashTable";
const string PktfwdSdnProvCompStaticCheck::FLOWENTRY = "flowEntry";
const string PktfwdSdnProvCompStaticCheck::INITPACKET = "initPacket";
const string PktfwdSdnProvCompStaticCheck::INITPACKETCOUNT = "initPacketCount";
const string PktfwdSdnProvCompStaticCheck::INITPACKETHASH = "initPacketHash";
const string PktfwdSdnProvCompStaticCheck::LINK = "link";
const string PktfwdSdnProvCompStaticCheck::LINKHR = "linkhr";
const string PktfwdSdnProvCompStaticCheck::MATCHINGPACKET = "matchingPacket";
const string PktfwdSdnProvCompStaticCheck::MATCHINGPACKETNONPROV = "matchingPacketNonProv";
const string PktfwdSdnProvCompStaticCheck::MAXPRIORITY = "maxPriority";
const string PktfwdSdnProvCompStaticCheck::PACKETNONPROV = "packetNonProv";
const string PktfwdSdnProvCompStaticCheck::PACKETPROV = "packetProv";
const string PktfwdSdnProvCompStaticCheck::PROVHASHTABLE = "provHashTable";
const string PktfwdSdnProvCompStaticCheck::RECVAUXPKT = "recvAuxPkt";
const string PktfwdSdnProvCompStaticCheck::RECVPACKET = "recvPacket";
const string PktfwdSdnProvCompStaticCheck::RECVPACKETDECOMP = "recvPacketDecomp";
const string PktfwdSdnProvCompStaticCheck::RECVPACKETTEMP = "recvPacketTemp";
const string PktfwdSdnProvCompStaticCheck::RULEEXEC = "ruleExec";

NS_LOG_COMPONENT_DEFINE ("PktfwdSdnProvCompStaticCheck");
NS_OBJECT_ENSURE_REGISTERED (PktfwdSdnProvCompStaticCheck);

TypeId
PktfwdSdnProvCompStaticCheck::GetTypeId (void)
{
  static TypeId tid = TypeId ("ns3::rapidnet::pktfwdsdnprovcompstaticcheck::PktfwdSdnProvCompStaticCheck")
    .SetParent<RapidNetApplicationBase> ()
    .AddConstructor<PktfwdSdnProvCompStaticCheck> ()
    ;
  return tid;
}

PktfwdSdnProvCompStaticCheck::PktfwdSdnProvCompStaticCheck()
{
  NS_LOG_FUNCTION_NOARGS ();
}

PktfwdSdnProvCompStaticCheck::~PktfwdSdnProvCompStaticCheck()
{
  NS_LOG_FUNCTION_NOARGS ();
}

void
PktfwdSdnProvCompStaticCheck::DoDispose (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::DoDispose ();
}

void
PktfwdSdnProvCompStaticCheck::StartApplication (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StartApplication ();
  RAPIDNET_LOG_INFO("PktfwdSdnProvCompStaticCheck Application Started");
}

void
PktfwdSdnProvCompStaticCheck::StopApplication ()
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StopApplication ();
  RAPIDNET_LOG_INFO("PktfwdSdnProvCompStaticCheck Application Stopped");
}

void
PktfwdSdnProvCompStaticCheck::InitDatabase ()
{
  //RapidNetApplicationBase::InitDatabase ();

  AddRelationWithKeys (DEVICE, attrdeflist (
    attrdef ("device_attr2", INT32)));

  AddRelationWithKeys (EQUIHASHTABLE, attrdeflist (
    attrdef ("equiHashTable_attr2", IPV4)));

  AddRelationWithKeys (FLOWENTRY, attrdeflist (
    attrdef ("flowEntry_attr2", IPV4),
    attrdef ("flowEntry_attr4", INT32)));

  AddRelationWithKeys (INITPACKET, attrdeflist (
    attrdef ("initPacket_attr2", IPV4),
    attrdef ("initPacket_attr3", IPV4),
    attrdef ("initPacket_attr4", STR)));

  AddRelationWithKeys (LINK, attrdeflist (
    attrdef ("link_attr2", IPV4)));

  AddRelationWithKeys (LINKHR, attrdeflist (
    attrdef ("linkhr_attr2", IPV4)));

  AddRelationWithKeys (MAXPRIORITY, attrdeflist (
    attrdef ("maxPriority_attr2", INT32)));

  AddRelationWithKeys (PROVHASHTABLE, attrdeflist (
    attrdef ("provHashTable_attr3", LIST)));

  AddRelationWithKeys (RECVAUXPKT, attrdeflist (
    attrdef ("recvAuxPkt_attr2", IPV4),
    attrdef ("recvAuxPkt_attr3", STR)));

  AddRelationWithKeys (RECVPACKET, attrdeflist (
    attrdef ("recvPacket_attr2", IPV4),
    attrdef ("recvPacket_attr3", IPV4),
    attrdef ("recvPacket_attr4", STR)));

  AddRelationWithKeys (RULEEXEC, attrdeflist (
    attrdef ("ruleExec_attr3", STR),
    attrdef ("ruleExec_attr4", LIST)));

}

void
PktfwdSdnProvCompStaticCheck::DemuxRecv (Ptr<Tuple> tuple)
{
  RapidNetApplicationBase::DemuxRecv (tuple);

  if (IsRecvEvent (tuple, PACKETPROV))
    {
      Rs10_eca (tuple);
    }
  if (IsRecvEvent (tuple, EMATCHINGPACKETTEMP))
    {
      Rs11_eca (tuple);
    }
  if (IsRecvEvent (tuple, EMATCHINGPACKETTEMP))
    {
      Rs12_eca (tuple);
    }
  if (IsRecvEvent (tuple, EMATCHINGPACKETCOUNT))
    {
      Rs13_eca (tuple);
    }
  if (IsRecvEvent (tuple, EMATCHINGPACKET))
    {
      Rs14_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKETNONPROV))
    {
      Rs1_eca (tuple);
    }
  if (IsRecvEvent (tuple, MATCHINGPACKET))
    {
      Rs20_eca (tuple);
    }
  if (IsRecvEvent (tuple, MATCHINGPACKETNONPROV))
    {
      Rs2_eca (tuple);
    }
  if (IsRecvEvent (tuple, MATCHINGPACKET))
    {
      Rs30_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPACKETTEMP))
    {
      Rs31_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPACKETTEMP))
    {
      Rs32_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPAKETCOUNT))
    {
      Rs33_eca (tuple);
    }
  if (IsRecvEvent (tuple, EPACKET))
    {
      Rs34_eca (tuple);
    }
  if (IsRecvEvent (tuple, MATCHINGPACKETNONPROV))
    {
      Rs3_eca (tuple);
    }
  if (IsRecvEvent (tuple, MATCHINGPACKET))
    {
      Rs40_eca (tuple);
    }
  if (IsRecvEvent (tuple, MATCHINGPACKETNONPROV))
    {
      Rs4_eca (tuple);
    }
  if (IsInsertEvent (tuple, INITPACKET))
    {
      Rh100Eca0Ins (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETHASH))
    {
      Rh101_eca (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETCOUNT))
    {
      Rh102_eca (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETCOUNT))
    {
      Rh103_eca (tuple);
    }
  if (IsRecvEvent (tuple, INITPACKETCOUNT))
    {
      Rh104_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKETPROV))
    {
      Rh20_eca (tuple);
    }
  if (IsRecvEvent (tuple, ERECVPACKETTEMP))
    {
      Rh21_eca (tuple);
    }
  if (IsRecvEvent (tuple, ERECVPACKETTEMP))
    {
      Rh22_eca (tuple);
    }
  if (IsRecvEvent (tuple, ERECVPACKETCOUNT))
    {
      Rs23_eca (tuple);
    }
  if (IsRecvEvent (tuple, ERECVPACKET))
    {
      Rh24_eca (tuple);
    }
  if (IsRecvEvent (tuple, RECVPACKETTEMP))
    {
      Rh25_eca (tuple);
    }
  if (IsRecvEvent (tuple, RECVPACKETDECOMP))
    {
      Rh26_eca (tuple);
    }
  if (IsRecvEvent (tuple, RECVPACKETDECOMP))
    {
      Rh27_eca (tuple);
    }
  if (IsRecvEvent (tuple, PACKETNONPROV))
    {
      Rh2_eca (tuple);
    }
  if (IsInsertEvent (tuple, RECVPACKET))
    {
      Rh28Eca0Ins (tuple);
    }
  if (IsDeleteEvent (tuple, RECVPACKET))
    {
      Rh28Eca0Del (tuple);
    }
}

void
PktfwdSdnProvCompStaticCheck::Rs10_eca (Ptr<Tuple> packetProv)
{
  RAPIDNET_LOG_INFO ("Rs10_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    packetProv,
    strlist ("device_attr1"),
    strlist ("packetProv_attr1"));

  result = GetRelation (MAXPRIORITY)->Join (
    result,
    strlist ("maxPriority_attr1"),
    strlist ("packetProv_attr1"));

  result->Assign (Assignor::New ("RLoc",
    VarExpr::New ("packetProv_attr1")));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rs1"))));

  result->Assign (Assignor::New ("PID1",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("device")),
          VarExpr::New ("packetProv_attr1")),
        VarExpr::New ("device_attr2")))));

  result->Assign (Assignor::New ("PID2",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("maxPriority")),
          VarExpr::New ("packetProv_attr1")),
        VarExpr::New ("maxPriority_attr2")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID1"))));

  result->Assign (Assignor::New ("List2",
    FAppend::New (
      VarExpr::New ("PID2"))));

  result->Assign (Assignor::New ("List",
    FConcat::New (
      VarExpr::New ("List"),
      VarExpr::New ("List2"))));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("R"),
        VarExpr::New ("List")))));

  result->Assign (Assignor::New ("DataList",
    FAppend::New (
      VarExpr::New ("packetProv_attr4"))));

  result->Assign (Assignor::New ("DataTag",
    FConcat::New (
      VarExpr::New ("DataList"),
      VarExpr::New ("packetProv_attr5"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    EMATCHINGPACKETTEMP,
    strlist ("RLoc",
      "packetProv_attr1",
      "packetProv_attr2",
      "packetProv_attr3",
      "maxPriority_attr2",
      "RID",
      "R",
      "List",
      "DataTag",
      "RLoc"),
    strlist ("eMatchingPacketTemp_attr1",
      "eMatchingPacketTemp_attr2",
      "eMatchingPacketTemp_attr3",
      "eMatchingPacketTemp_attr4",
      "eMatchingPacketTemp_attr5",
      "eMatchingPacketTemp_attr6",
      "eMatchingPacketTemp_attr7",
      "eMatchingPacketTemp_attr8",
      "eMatchingPacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs11_eca (Ptr<Tuple> eMatchingPacketTemp)
{
  RAPIDNET_LOG_INFO ("Rs11_eca triggered");

  Ptr<Tuple> result = eMatchingPacketTemp;

  result->Assign (Assignor::New ("Data",
    FFirst::New (
      VarExpr::New ("eMatchingPacketTemp_attr9"))));

  result->Assign (Assignor::New ("Tag",
    FRemoveFirst::New (
      VarExpr::New ("eMatchingPacketTemp_attr9"))));

  result = result->Project (
    EMATCHINGPACKET,
    strlist ("eMatchingPacketTemp_attr2",
      "eMatchingPacketTemp_attr3",
      "eMatchingPacketTemp_attr4",
      "Data",
      "eMatchingPacketTemp_attr5",
      "eMatchingPacketTemp_attr6",
      "eMatchingPacketTemp_attr1",
      "Tag",
      "eMatchingPacketTemp_attr2"),
    strlist ("eMatchingPacket_attr1",
      "eMatchingPacket_attr2",
      "eMatchingPacket_attr3",
      "eMatchingPacket_attr4",
      "eMatchingPacket_attr5",
      "eMatchingPacket_attr6",
      "eMatchingPacket_attr7",
      "eMatchingPacket_attr8",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs12_eca (Ptr<Tuple> eMatchingPacketTemp)
{
  RAPIDNET_LOG_INFO ("Rs12_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (RULEEXEC)->Join (
    eMatchingPacketTemp,
    strlist ("ruleExec_attr4", "ruleExec_attr3", "ruleExec_attr2", "ruleExec_attr1"),
    strlist ("eMatchingPacketTemp_attr8", "eMatchingPacketTemp_attr7", "eMatchingPacketTemp_attr6", "eMatchingPacketTemp_attr1"));

  result = AggWrapCount::New ()->Compute (result, eMatchingPacketTemp);

  result = result->Project (
    EMATCHINGPACKETCOUNT,
    strlist ("eMatchingPacketTemp_attr1",
      "eMatchingPacketTemp_attr6",
      "eMatchingPacketTemp_attr7",
      "eMatchingPacketTemp_attr8",
      "count"),
    strlist ("eMatchingPacketCount_attr1",
      "eMatchingPacketCount_attr2",
      "eMatchingPacketCount_attr3",
      "eMatchingPacketCount_attr4",
      "eMatchingPacketCount_attr5"));

  SendLocal (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs13_eca (Ptr<Tuple> eMatchingPacketCount)
{
  RAPIDNET_LOG_INFO ("Rs13_eca triggered");

  Ptr<Tuple> result = eMatchingPacketCount;

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("eMatchingPacketCount_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    RULEEXEC,
    strlist ("eMatchingPacketCount_attr1",
      "eMatchingPacketCount_attr2",
      "eMatchingPacketCount_attr3",
      "eMatchingPacketCount_attr4"),
    strlist ("ruleExec_attr1",
      "ruleExec_attr2",
      "ruleExec_attr3",
      "ruleExec_attr4"));

  Insert (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs14_eca (Ptr<Tuple> eMatchingPacket)
{
  RAPIDNET_LOG_INFO ("Rs14_eca triggered");

  Ptr<Tuple> result = eMatchingPacket;

  result->Assign (Assignor::New ("Hash",
    FAppend::New (
      VarExpr::New ("eMatchingPacket_attr6"))));

  result->Assign (Assignor::New ("NewTag",
    FConcat::New (
      VarExpr::New ("eMatchingPacket_attr8"),
      VarExpr::New ("Hash"))));

  result = result->Project (
    MATCHINGPACKET,
    strlist ("eMatchingPacket_attr1",
      "eMatchingPacket_attr2",
      "eMatchingPacket_attr3",
      "eMatchingPacket_attr4",
      "eMatchingPacket_attr5",
      "NewTag"),
    strlist ("matchingPacket_attr1",
      "matchingPacket_attr2",
      "matchingPacket_attr3",
      "matchingPacket_attr4",
      "matchingPacket_attr5",
      "matchingPacket_attr6"));

  SendLocal (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs1_eca (Ptr<Tuple> packetNonProv)
{
  RAPIDNET_LOG_INFO ("Rs1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    packetNonProv,
    strlist ("device_attr1"),
    strlist ("packetNonProv_attr1"));

  result = GetRelation (MAXPRIORITY)->Join (
    result,
    strlist ("maxPriority_attr1"),
    strlist ("packetNonProv_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    MATCHINGPACKETNONPROV,
    strlist ("packetNonProv_attr1",
      "packetNonProv_attr2",
      "packetNonProv_attr3",
      "packetNonProv_attr4",
      "maxPriority_attr2",
      "packetNonProv_attr5",
      "packetNonProv_attr6"),
    strlist ("matchingPacketNonProv_attr1",
      "matchingPacketNonProv_attr2",
      "matchingPacketNonProv_attr3",
      "matchingPacketNonProv_attr4",
      "matchingPacketNonProv_attr5",
      "matchingPacketNonProv_attr6",
      "matchingPacketNonProv_attr7"));

  SendLocal (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs20_eca (Ptr<Tuple> matchingPacket)
{
  RAPIDNET_LOG_INFO ("Rs20_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    matchingPacket,
    strlist ("device_attr1"),
    strlist ("matchingPacket_attr1"));

  result = GetRelation (FLOWENTRY)->Join (
    result,
    strlist ("flowEntry_attr4", "flowEntry_attr1"),
    strlist ("matchingPacket_attr5", "matchingPacket_attr1"));

  result->Assign (Assignor::New ("NextPriority",
    Operation::New (RN_MINUS,
      VarExpr::New ("matchingPacket_attr5"),
      ValueExpr::New (Int32Value::New (1)))));

  result->Assign (Assignor::New ("RLoc",
    VarExpr::New ("matchingPacket_attr1")));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rs2"))));

  result->Assign (Assignor::New ("PID1",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("device")),
          VarExpr::New ("matchingPacket_attr1")),
        VarExpr::New ("device_attr2")))));

  result->Assign (Assignor::New ("PID2",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("flowEntry")),
              VarExpr::New ("matchingPacket_attr1")),
            VarExpr::New ("flowEntry_attr2")),
          VarExpr::New ("flowEntry_attr3")),
        VarExpr::New ("matchingPacket_attr5")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID1"))));

  result->Assign (Assignor::New ("List2",
    FAppend::New (
      VarExpr::New ("PID2"))));

  result->Assign (Assignor::New ("List",
    FConcat::New (
      VarExpr::New ("List"),
      VarExpr::New ("List2"))));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("R"),
        VarExpr::New ("List")))));

  result->Assign (Assignor::New ("DataList",
    FAppend::New (
      VarExpr::New ("matchingPacket_attr4"))));

  result->Assign (Assignor::New ("DataTag",
    FConcat::New (
      VarExpr::New ("DataList"),
      VarExpr::New ("matchingPacket_attr6"))));

  result = result->Select (Selector::New (
    Operation::New (RN_GT,
      VarExpr::New ("matchingPacket_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Select (Selector::New (
    Operation::New (RN_NEQ,
      VarExpr::New ("matchingPacket_attr3"),
      VarExpr::New ("flowEntry_attr2"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    EMATCHINGPACKETTEMP,
    strlist ("RLoc",
      "matchingPacket_attr1",
      "matchingPacket_attr2",
      "matchingPacket_attr3",
      "NextPriority",
      "RID",
      "R",
      "List",
      "DataTag",
      "RLoc"),
    strlist ("eMatchingPacketTemp_attr1",
      "eMatchingPacketTemp_attr2",
      "eMatchingPacketTemp_attr3",
      "eMatchingPacketTemp_attr4",
      "eMatchingPacketTemp_attr5",
      "eMatchingPacketTemp_attr6",
      "eMatchingPacketTemp_attr7",
      "eMatchingPacketTemp_attr8",
      "eMatchingPacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs2_eca (Ptr<Tuple> matchingPacketNonProv)
{
  RAPIDNET_LOG_INFO ("Rs2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    matchingPacketNonProv,
    strlist ("device_attr1"),
    strlist ("matchingPacketNonProv_attr1"));

  result = GetRelation (FLOWENTRY)->Join (
    result,
    strlist ("flowEntry_attr4", "flowEntry_attr1"),
    strlist ("matchingPacketNonProv_attr5", "matchingPacketNonProv_attr1"));

  result->Assign (Assignor::New ("NextPriority",
    Operation::New (RN_MINUS,
      VarExpr::New ("matchingPacketNonProv_attr5"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Select (Selector::New (
    Operation::New (RN_GT,
      VarExpr::New ("matchingPacketNonProv_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Select (Selector::New (
    Operation::New (RN_NEQ,
      VarExpr::New ("matchingPacketNonProv_attr3"),
      VarExpr::New ("flowEntry_attr2"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    MATCHINGPACKETNONPROV,
    strlist ("matchingPacketNonProv_attr1",
      "matchingPacketNonProv_attr2",
      "matchingPacketNonProv_attr3",
      "matchingPacketNonProv_attr4",
      "NextPriority",
      "matchingPacketNonProv_attr6",
      "matchingPacketNonProv_attr7"),
    strlist ("matchingPacketNonProv_attr1",
      "matchingPacketNonProv_attr2",
      "matchingPacketNonProv_attr3",
      "matchingPacketNonProv_attr4",
      "matchingPacketNonProv_attr5",
      "matchingPacketNonProv_attr6",
      "matchingPacketNonProv_attr7"));

  SendLocal (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs30_eca (Ptr<Tuple> matchingPacket)
{
  RAPIDNET_LOG_INFO ("Rs30_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    matchingPacket,
    strlist ("device_attr1"),
    strlist ("matchingPacket_attr1"));

  result = GetRelation (FLOWENTRY)->Join (
    result,
    strlist ("flowEntry_attr4", "flowEntry_attr1"),
    strlist ("matchingPacket_attr5", "matchingPacket_attr1"));

  result = GetRelation (LINK)->Join (
    result,
    strlist ("link_attr2", "link_attr1"),
    strlist ("flowEntry_attr3", "matchingPacket_attr1"));

  result->Assign (Assignor::New ("RLoc",
    VarExpr::New ("matchingPacket_attr1")));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rs3"))));

  result->Assign (Assignor::New ("PID1",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("device")),
          VarExpr::New ("matchingPacket_attr1")),
        VarExpr::New ("device_attr2")))));

  result->Assign (Assignor::New ("PID2",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("flowEntry")),
              VarExpr::New ("matchingPacket_attr1")),
            VarExpr::New ("flowEntry_attr2")),
          VarExpr::New ("flowEntry_attr3")),
        VarExpr::New ("matchingPacket_attr5")))));

  result->Assign (Assignor::New ("PID3",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("link")),
          VarExpr::New ("matchingPacket_attr1")),
        VarExpr::New ("flowEntry_attr3")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID1"))));

  result->Assign (Assignor::New ("List2",
    FAppend::New (
      VarExpr::New ("PID2"))));

  result->Assign (Assignor::New ("List",
    FConcat::New (
      VarExpr::New ("List"),
      VarExpr::New ("List2"))));

  result->Assign (Assignor::New ("List3",
    FAppend::New (
      VarExpr::New ("PID3"))));

  result->Assign (Assignor::New ("List",
    FConcat::New (
      VarExpr::New ("List"),
      VarExpr::New ("List3"))));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("R"),
        VarExpr::New ("List")))));

  result = result->Select (Selector::New (
    Operation::New (RN_GT,
      VarExpr::New ("matchingPacket_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("matchingPacket_attr3"),
      VarExpr::New ("flowEntry_attr2"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    EPACKETTEMP,
    strlist ("RLoc",
      "flowEntry_attr3",
      "matchingPacket_attr2",
      "matchingPacket_attr3",
      "matchingPacket_attr4",
      "RID",
      "R",
      "List",
      "matchingPacket_attr6",
      "RLoc"),
    strlist ("ePacketTemp_attr1",
      "ePacketTemp_attr2",
      "ePacketTemp_attr3",
      "ePacketTemp_attr4",
      "ePacketTemp_attr5",
      "ePacketTemp_attr6",
      "ePacketTemp_attr7",
      "ePacketTemp_attr8",
      "ePacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs31_eca (Ptr<Tuple> ePacketTemp)
{
  RAPIDNET_LOG_INFO ("Rs31_eca triggered");

  Ptr<Tuple> result = ePacketTemp;

  result = result->Project (
    EPACKET,
    strlist ("ePacketTemp_attr2",
      "ePacketTemp_attr3",
      "ePacketTemp_attr4",
      "ePacketTemp_attr5",
      "ePacketTemp_attr6",
      "ePacketTemp_attr1",
      "ePacketTemp_attr9",
      "ePacketTemp_attr2"),
    strlist ("ePacket_attr1",
      "ePacket_attr2",
      "ePacket_attr3",
      "ePacket_attr4",
      "ePacket_attr5",
      "ePacket_attr6",
      "ePacket_attr7",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs32_eca (Ptr<Tuple> ePacketTemp)
{
  RAPIDNET_LOG_INFO ("Rs32_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (RULEEXEC)->Join (
    ePacketTemp,
    strlist ("ruleExec_attr4", "ruleExec_attr3", "ruleExec_attr2", "ruleExec_attr1"),
    strlist ("ePacketTemp_attr8", "ePacketTemp_attr7", "ePacketTemp_attr6", "ePacketTemp_attr1"));

  result = AggWrapCount::New ()->Compute (result, ePacketTemp);

  result = result->Project (
    EPAKETCOUNT,
    strlist ("ePacketTemp_attr1",
      "ePacketTemp_attr6",
      "ePacketTemp_attr7",
      "ePacketTemp_attr8",
      "count"),
    strlist ("ePaketCount_attr1",
      "ePaketCount_attr2",
      "ePaketCount_attr3",
      "ePaketCount_attr4",
      "ePaketCount_attr5"));

  SendLocal (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs33_eca (Ptr<Tuple> ePaketCount)
{
  RAPIDNET_LOG_INFO ("Rs33_eca triggered");

  Ptr<Tuple> result = ePaketCount;

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("ePaketCount_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    RULEEXEC,
    strlist ("ePaketCount_attr1",
      "ePaketCount_attr2",
      "ePaketCount_attr3",
      "ePaketCount_attr4"),
    strlist ("ruleExec_attr1",
      "ruleExec_attr2",
      "ruleExec_attr3",
      "ruleExec_attr4"));

  Insert (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs34_eca (Ptr<Tuple> ePacket)
{
  RAPIDNET_LOG_INFO ("Rs34_eca triggered");

  Ptr<Tuple> result = ePacket;

  result->Assign (Assignor::New ("Hash",
    FAppend::New (
      VarExpr::New ("ePacket_attr5"))));

  result->Assign (Assignor::New ("NewTag",
    FConcat::New (
      VarExpr::New ("ePacket_attr7"),
      VarExpr::New ("Hash"))));

  result = result->Project (
    PACKETPROV,
    strlist ("ePacket_attr1",
      "ePacket_attr2",
      "ePacket_attr3",
      "ePacket_attr4",
      "NewTag"),
    strlist ("packetProv_attr1",
      "packetProv_attr2",
      "packetProv_attr3",
      "packetProv_attr4",
      "packetProv_attr5"));

  SendLocal (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs3_eca (Ptr<Tuple> matchingPacketNonProv)
{
  RAPIDNET_LOG_INFO ("Rs3_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    matchingPacketNonProv,
    strlist ("device_attr1"),
    strlist ("matchingPacketNonProv_attr1"));

  result = GetRelation (FLOWENTRY)->Join (
    result,
    strlist ("flowEntry_attr4", "flowEntry_attr1"),
    strlist ("matchingPacketNonProv_attr5", "matchingPacketNonProv_attr1"));

  result = GetRelation (LINK)->Join (
    result,
    strlist ("link_attr2", "link_attr1"),
    strlist ("flowEntry_attr3", "matchingPacketNonProv_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_GT,
      VarExpr::New ("matchingPacketNonProv_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("matchingPacketNonProv_attr3"),
      VarExpr::New ("flowEntry_attr2"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    PACKETNONPROV,
    strlist ("flowEntry_attr3",
      "matchingPacketNonProv_attr2",
      "matchingPacketNonProv_attr3",
      "matchingPacketNonProv_attr4",
      "matchingPacketNonProv_attr6",
      "matchingPacketNonProv_attr7",
      "flowEntry_attr3"),
    strlist ("packetNonProv_attr1",
      "packetNonProv_attr2",
      "packetNonProv_attr3",
      "packetNonProv_attr4",
      "packetNonProv_attr5",
      "packetNonProv_attr6",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs40_eca (Ptr<Tuple> matchingPacket)
{
  RAPIDNET_LOG_INFO ("Rs40_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    matchingPacket,
    strlist ("device_attr1"),
    strlist ("matchingPacket_attr1"));

  result = GetRelation (FLOWENTRY)->Join (
    result,
    strlist ("flowEntry_attr2", "flowEntry_attr4", "flowEntry_attr1"),
    strlist ("matchingPacket_attr3", "matchingPacket_attr5", "matchingPacket_attr1"));

  result = GetRelation (LINK)->Join (
    result,
    strlist ("link_attr2", "link_attr1"),
    strlist ("flowEntry_attr3", "matchingPacket_attr1"));

  result->Assign (Assignor::New ("RLoc",
    VarExpr::New ("matchingPacket_attr1")));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rs4"))));

  result->Assign (Assignor::New ("PID1",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("device")),
          VarExpr::New ("matchingPacket_attr1")),
        VarExpr::New ("device_attr2")))));

  result->Assign (Assignor::New ("PID2",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("flowEntry")),
              VarExpr::New ("matchingPacket_attr1")),
            VarExpr::New ("matchingPacket_attr3")),
          VarExpr::New ("flowEntry_attr3")),
        VarExpr::New ("matchingPacket_attr5")))));

  result->Assign (Assignor::New ("PID3",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("link")),
          VarExpr::New ("matchingPacket_attr1")),
        VarExpr::New ("flowEntry_attr3")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID1"))));

  result->Assign (Assignor::New ("List2",
    FAppend::New (
      VarExpr::New ("PID2"))));

  result->Assign (Assignor::New ("List",
    FConcat::New (
      VarExpr::New ("List"),
      VarExpr::New ("List2"))));

  result->Assign (Assignor::New ("List3",
    FAppend::New (
      VarExpr::New ("PID3"))));

  result->Assign (Assignor::New ("List",
    FConcat::New (
      VarExpr::New ("List"),
      VarExpr::New ("List3"))));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("R"),
        VarExpr::New ("List")))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("matchingPacket_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    EPACKETTEMP,
    strlist ("RLoc",
      "flowEntry_attr3",
      "matchingPacket_attr2",
      "matchingPacket_attr3",
      "matchingPacket_attr4",
      "RID",
      "R",
      "List",
      "matchingPacket_attr6",
      "RLoc"),
    strlist ("ePacketTemp_attr1",
      "ePacketTemp_attr2",
      "ePacketTemp_attr3",
      "ePacketTemp_attr4",
      "ePacketTemp_attr5",
      "ePacketTemp_attr6",
      "ePacketTemp_attr7",
      "ePacketTemp_attr8",
      "ePacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs4_eca (Ptr<Tuple> matchingPacketNonProv)
{
  RAPIDNET_LOG_INFO ("Rs4_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    matchingPacketNonProv,
    strlist ("device_attr1"),
    strlist ("matchingPacketNonProv_attr1"));

  result = GetRelation (FLOWENTRY)->Join (
    result,
    strlist ("flowEntry_attr2", "flowEntry_attr4", "flowEntry_attr1"),
    strlist ("matchingPacketNonProv_attr3", "matchingPacketNonProv_attr5", "matchingPacketNonProv_attr1"));

  result = GetRelation (LINK)->Join (
    result,
    strlist ("link_attr2", "link_attr1"),
    strlist ("flowEntry_attr3", "matchingPacketNonProv_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("matchingPacketNonProv_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    PACKETNONPROV,
    strlist ("flowEntry_attr3",
      "matchingPacketNonProv_attr2",
      "matchingPacketNonProv_attr3",
      "matchingPacketNonProv_attr4",
      "matchingPacketNonProv_attr6",
      "matchingPacketNonProv_attr7",
      "flowEntry_attr3"),
    strlist ("packetNonProv_attr1",
      "packetNonProv_attr2",
      "packetNonProv_attr3",
      "packetNonProv_attr4",
      "packetNonProv_attr5",
      "packetNonProv_attr6",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh100Eca0Ins (Ptr<Tuple> initPacket)
{
  RAPIDNET_LOG_INFO ("Rh100Eca0Ins triggered");

  Ptr<Tuple> result = initPacket;

  result->Assign (Assignor::New ("PIDequi",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("")),
          VarExpr::New ("initPacket_attr1")),
        VarExpr::New ("initPacket_attr3")))));

  result = result->Project (
    INITPACKETHASH,
    strlist ("initPacket_attr1",
      "initPacket_attr2",
      "initPacket_attr3",
      "initPacket_attr4",
      "PIDequi"),
    strlist ("initPacketHash_attr1",
      "initPacketHash_attr2",
      "initPacketHash_attr3",
      "initPacketHash_attr4",
      "initPacketHash_attr5"));

  SendLocal (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh101_eca (Ptr<Tuple> initPacketHash)
{
  RAPIDNET_LOG_INFO ("Rh101_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (EQUIHASHTABLE)->Join (
    initPacketHash,
    strlist ("equiHashTable_attr2", "equiHashTable_attr1", "equiHashTable_attr3"),
    strlist ("initPacketHash_attr3", "initPacketHash_attr1", "initPacketHash_attr5"));

  result = AggWrapCount::New ()->Compute (result, initPacketHash);

  result = result->Project (
    INITPACKETCOUNT,
    strlist ("initPacketHash_attr1",
      "initPacketHash_attr2",
      "initPacketHash_attr3",
      "initPacketHash_attr4",
      "initPacketHash_attr5",
      "count"),
    strlist ("initPacketCount_attr1",
      "initPacketCount_attr2",
      "initPacketCount_attr3",
      "initPacketCount_attr4",
      "initPacketCount_attr5",
      "initPacketCount_attr6"));

  SendLocal (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh102_eca (Ptr<Tuple> initPacketCount)
{
  RAPIDNET_LOG_INFO ("Rh102_eca triggered");

  Ptr<Tuple> result = initPacketCount;

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("initPacketCount_attr6"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    EQUIHASHTABLE,
    strlist ("initPacketCount_attr1",
      "initPacketCount_attr3",
      "initPacketCount_attr5"),
    strlist ("equiHashTable_attr1",
      "equiHashTable_attr2",
      "equiHashTable_attr3"));

  Insert (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh103_eca (Ptr<Tuple> initPacketCount)
{
  RAPIDNET_LOG_INFO ("Rh103_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    initPacketCount,
    strlist ("device_attr1"),
    strlist ("initPacketCount_attr1"));

  result = GetRelation (LINKHR)->Join (
    result,
    strlist ("linkhr_attr1"),
    strlist ("initPacketCount_attr1"));

  result->Assign (Assignor::New ("PIDev",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("initPacket")),
              VarExpr::New ("initPacketCount_attr1")),
            VarExpr::New ("initPacketCount_attr2")),
          VarExpr::New ("initPacketCount_attr3")),
        VarExpr::New ("initPacketCount_attr4")))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Select (Selector::New (
    Operation::New (RN_NEQ,
      VarExpr::New ("initPacketCount_attr6"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    PACKETNONPROV,
    strlist ("linkhr_attr2",
      "initPacketCount_attr2",
      "initPacketCount_attr3",
      "initPacketCount_attr4",
      "initPacketCount_attr5",
      "PIDev",
      "linkhr_attr2"),
    strlist ("packetNonProv_attr1",
      "packetNonProv_attr2",
      "packetNonProv_attr3",
      "packetNonProv_attr4",
      "packetNonProv_attr5",
      "packetNonProv_attr6",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh104_eca (Ptr<Tuple> initPacketCount)
{
  RAPIDNET_LOG_INFO ("Rh104_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    initPacketCount,
    strlist ("device_attr1"),
    strlist ("initPacketCount_attr1"));

  result = GetRelation (LINKHR)->Join (
    result,
    strlist ("linkhr_attr1"),
    strlist ("initPacketCount_attr1"));

  result->Assign (Assignor::New ("RLoc",
    VarExpr::New ("initPacketCount_attr1")));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rh1"))));

  result->Assign (Assignor::New ("PIDev",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          Operation::New (RN_PLUS,
            Operation::New (RN_PLUS,
              ValueExpr::New (StrValue::New ("initPacket")),
              VarExpr::New ("initPacketCount_attr1")),
            VarExpr::New ("initPacketCount_attr2")),
          VarExpr::New ("initPacketCount_attr3")),
        VarExpr::New ("initPacketCount_attr4")))));

  result->Assign (Assignor::New ("Equilist",
    FAppend::New (
      VarExpr::New ("initPacketCount_attr5"))));

  result->Assign (Assignor::New ("Evlist",
    FAppend::New (
      VarExpr::New ("PIDev"))));

  result->Assign (Assignor::New ("Tag",
    FConcat::New (
      VarExpr::New ("Equilist"),
      VarExpr::New ("Evlist"))));

  result->Assign (Assignor::New ("PID1",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("device")),
          VarExpr::New ("initPacketCount_attr1")),
        VarExpr::New ("device_attr2")))));

  result->Assign (Assignor::New ("PID2",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("linkhr")),
          VarExpr::New ("initPacketCount_attr1")),
        VarExpr::New ("linkhr_attr2")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID1"))));

  result->Assign (Assignor::New ("List2",
    FAppend::New (
      VarExpr::New ("PID2"))));

  result->Assign (Assignor::New ("List",
    FConcat::New (
      VarExpr::New ("List"),
      VarExpr::New ("List2"))));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("R"),
        VarExpr::New ("List")))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("initPacketCount_attr6"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    EPACKETTEMP,
    strlist ("RLoc",
      "linkhr_attr2",
      "initPacketCount_attr2",
      "initPacketCount_attr3",
      "initPacketCount_attr4",
      "RID",
      "R",
      "List",
      "Tag",
      "RLoc"),
    strlist ("ePacketTemp_attr1",
      "ePacketTemp_attr2",
      "ePacketTemp_attr3",
      "ePacketTemp_attr4",
      "ePacketTemp_attr5",
      "ePacketTemp_attr6",
      "ePacketTemp_attr7",
      "ePacketTemp_attr8",
      "ePacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh20_eca (Ptr<Tuple> packetProv)
{
  RAPIDNET_LOG_INFO ("Rh20_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    packetProv,
    strlist ("device_attr1"),
    strlist ("packetProv_attr1"));

  result->Assign (Assignor::New ("RLoc",
    VarExpr::New ("packetProv_attr1")));

  result->Assign (Assignor::New ("R",
    ValueExpr::New (StrValue::New ("rh2"))));

  result->Assign (Assignor::New ("PID1",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("device")),
          VarExpr::New ("packetProv_attr1")),
        VarExpr::New ("device_attr2")))));

  result->Assign (Assignor::New ("List",
    FAppend::New (
      VarExpr::New ("PID1"))));

  result->Assign (Assignor::New ("RID",
    FSha1::New (
      Operation::New (RN_PLUS,
        VarExpr::New ("R"),
        VarExpr::New ("List")))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("packetProv_attr3"),
      VarExpr::New ("packetProv_attr1"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    ERECVPACKETTEMP,
    strlist ("RLoc",
      "packetProv_attr1",
      "packetProv_attr2",
      "packetProv_attr3",
      "packetProv_attr4",
      "RID",
      "R",
      "List",
      "packetProv_attr5",
      "RLoc"),
    strlist ("eRecvPacketTemp_attr1",
      "eRecvPacketTemp_attr2",
      "eRecvPacketTemp_attr3",
      "eRecvPacketTemp_attr4",
      "eRecvPacketTemp_attr5",
      "eRecvPacketTemp_attr6",
      "eRecvPacketTemp_attr7",
      "eRecvPacketTemp_attr8",
      "eRecvPacketTemp_attr9",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh21_eca (Ptr<Tuple> eRecvPacketTemp)
{
  RAPIDNET_LOG_INFO ("Rh21_eca triggered");

  Ptr<Tuple> result = eRecvPacketTemp;

  result = result->Project (
    ERECVPACKET,
    strlist ("eRecvPacketTemp_attr2",
      "eRecvPacketTemp_attr3",
      "eRecvPacketTemp_attr4",
      "eRecvPacketTemp_attr5",
      "eRecvPacketTemp_attr6",
      "eRecvPacketTemp_attr1",
      "eRecvPacketTemp_attr9",
      "eRecvPacketTemp_attr2"),
    strlist ("eRecvPacket_attr1",
      "eRecvPacket_attr2",
      "eRecvPacket_attr3",
      "eRecvPacket_attr4",
      "eRecvPacket_attr5",
      "eRecvPacket_attr6",
      "eRecvPacket_attr7",
      RN_DEST));

  Send (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh22_eca (Ptr<Tuple> eRecvPacketTemp)
{
  RAPIDNET_LOG_INFO ("Rh22_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (RULEEXEC)->Join (
    eRecvPacketTemp,
    strlist ("ruleExec_attr4", "ruleExec_attr3", "ruleExec_attr2", "ruleExec_attr1"),
    strlist ("eRecvPacketTemp_attr8", "eRecvPacketTemp_attr7", "eRecvPacketTemp_attr6", "eRecvPacketTemp_attr1"));

  result = AggWrapCount::New ()->Compute (result, eRecvPacketTemp);

  result = result->Project (
    ERECVPACKETCOUNT,
    strlist ("eRecvPacketTemp_attr1",
      "eRecvPacketTemp_attr6",
      "eRecvPacketTemp_attr7",
      "eRecvPacketTemp_attr8",
      "count"),
    strlist ("eRecvPacketCount_attr1",
      "eRecvPacketCount_attr2",
      "eRecvPacketCount_attr3",
      "eRecvPacketCount_attr4",
      "eRecvPacketCount_attr5"));

  SendLocal (result);
}

void
PktfwdSdnProvCompStaticCheck::Rs23_eca (Ptr<Tuple> eRecvPacketCount)
{
  RAPIDNET_LOG_INFO ("Rs23_eca triggered");

  Ptr<Tuple> result = eRecvPacketCount;

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("eRecvPacketCount_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    RULEEXEC,
    strlist ("eRecvPacketCount_attr1",
      "eRecvPacketCount_attr2",
      "eRecvPacketCount_attr3",
      "eRecvPacketCount_attr4"),
    strlist ("ruleExec_attr1",
      "ruleExec_attr2",
      "ruleExec_attr3",
      "ruleExec_attr4"));

  Insert (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh24_eca (Ptr<Tuple> eRecvPacket)
{
  RAPIDNET_LOG_INFO ("Rh24_eca triggered");

  Ptr<Tuple> result = eRecvPacket;

  result->Assign (Assignor::New ("Hash",
    FAppend::New (
      VarExpr::New ("eRecvPacket_attr5"))));

  result->Assign (Assignor::New ("NewTag",
    FConcat::New (
      VarExpr::New ("eRecvPacket_attr7"),
      VarExpr::New ("Hash"))));

  result = result->Project (
    RECVPACKETTEMP,
    strlist ("eRecvPacket_attr1",
      "eRecvPacket_attr2",
      "eRecvPacket_attr3",
      "eRecvPacket_attr4",
      "eRecvPacket_attr7"),
    strlist ("recvPacketTemp_attr1",
      "recvPacketTemp_attr2",
      "recvPacketTemp_attr3",
      "recvPacketTemp_attr4",
      "recvPacketTemp_attr5"));

  SendLocal (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh25_eca (Ptr<Tuple> recvPacketTemp)
{
  RAPIDNET_LOG_INFO ("Rh25_eca triggered");

  Ptr<Tuple> result = recvPacketTemp;

  result->Assign (Assignor::New ("PIDequi",
    FFirst::New (
      VarExpr::New ("recvPacketTemp_attr5"))));

  result->Assign (Assignor::New ("Remainlist",
    FRemoveFirst::New (
      VarExpr::New ("recvPacketTemp_attr5"))));

  result->Assign (Assignor::New ("PIDev",
    FFirst::New (
      VarExpr::New ("Remainlist"))));

  result->Assign (Assignor::New ("Hashlist",
    FRemoveFirst::New (
      VarExpr::New ("Remainlist"))));

  result = result->Project (
    RECVPACKETDECOMP,
    strlist ("recvPacketTemp_attr1",
      "recvPacketTemp_attr2",
      "recvPacketTemp_attr3",
      "recvPacketTemp_attr4",
      "PIDequi",
      "PIDev",
      "Hashlist"),
    strlist ("recvPacketDecomp_attr1",
      "recvPacketDecomp_attr2",
      "recvPacketDecomp_attr3",
      "recvPacketDecomp_attr4",
      "recvPacketDecomp_attr5",
      "recvPacketDecomp_attr6",
      "recvPacketDecomp_attr7"));

  SendLocal (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh26_eca (Ptr<Tuple> recvPacketDecomp)
{
  RAPIDNET_LOG_INFO ("Rh26_eca triggered");

  Ptr<Tuple> result = recvPacketDecomp;

  result = result->Project (
    PROVHASHTABLE,
    strlist ("recvPacketDecomp_attr1",
      "recvPacketDecomp_attr5",
      "recvPacketDecomp_attr7"),
    strlist ("provHashTable_attr1",
      "provHashTable_attr2",
      "provHashTable_attr3"));

  Insert (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh27_eca (Ptr<Tuple> recvPacketDecomp)
{
  RAPIDNET_LOG_INFO ("Rh27_eca triggered");

  Ptr<Tuple> result = recvPacketDecomp;

  result = result->Project (
    RECVPACKET,
    strlist ("recvPacketDecomp_attr1",
      "recvPacketDecomp_attr2",
      "recvPacketDecomp_attr3",
      "recvPacketDecomp_attr4",
      "recvPacketDecomp_attr5",
      "recvPacketDecomp_attr6"),
    strlist ("recvPacket_attr1",
      "recvPacket_attr2",
      "recvPacket_attr3",
      "recvPacket_attr4",
      "recvPacket_attr5",
      "recvPacket_attr6"));

  Insert (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh2_eca (Ptr<Tuple> packetNonProv)
{
  RAPIDNET_LOG_INFO ("Rh2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    packetNonProv,
    strlist ("device_attr1"),
    strlist ("packetNonProv_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    RECVPACKET,
    strlist ("packetNonProv_attr1",
      "packetNonProv_attr2",
      "packetNonProv_attr3",
      "packetNonProv_attr4",
      "packetNonProv_attr5",
      "packetNonProv_attr6"),
    strlist ("recvPacket_attr1",
      "recvPacket_attr2",
      "recvPacket_attr3",
      "recvPacket_attr4",
      "recvPacket_attr5",
      "recvPacket_attr6"));

  Insert (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh28Eca0Ins (Ptr<Tuple> recvPacket)
{
  RAPIDNET_LOG_INFO ("Rh28Eca0Ins triggered");

  Ptr<Tuple> result = recvPacket;

  result = result->Project (
    RECVAUXPKT,
    strlist ("recvPacket_attr1",
      "recvPacket_attr2",
      "recvPacket_attr4",
      "recvPacket_attr5",
      "recvPacket_attr6"),
    strlist ("recvAuxPkt_attr1",
      "recvAuxPkt_attr2",
      "recvAuxPkt_attr3",
      "recvAuxPkt_attr4",
      "recvAuxPkt_attr5"));

  Insert (result);
}

void
PktfwdSdnProvCompStaticCheck::Rh28Eca0Del (Ptr<Tuple> recvPacket)
{
  RAPIDNET_LOG_INFO ("Rh28Eca0Del triggered");

  Ptr<Tuple> result = recvPacket;

  result = result->Project (
    RECVAUXPKT,
    strlist ("recvPacket_attr1",
      "recvPacket_attr2",
      "recvPacket_attr4",
      "recvPacket_attr5",
      "recvPacket_attr6"),
    strlist ("recvAuxPkt_attr1",
      "recvAuxPkt_attr2",
      "recvAuxPkt_attr3",
      "recvAuxPkt_attr4",
      "recvAuxPkt_attr5"));

  Delete (result);
}

