## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pktfwd-sdn-prov-comp-static-check', ['internet-stack'])
    module.source = [
        'pktfwd-sdn-prov-comp-static-check.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pktfwd-sdn-prov-comp-static-check'
    headers.source = [
        'pktfwd-sdn-prov-comp-static-check.h',
        'pktfwd-sdn-prov-comp-static-check-helper.h',
        ]
