/* A RapidNet application. Generated by RapidNet compiler. */

#include "pktfwd-sdn.h"
#include <cstdlib>
#include "ns3/nstime.h"
#include "ns3/simulator.h"
#include "ns3/type-ids.h"
#include "ns3/rapidnet-types.h"
#include "ns3/rapidnet-utils.h"
#include "ns3/assignor.h"
#include "ns3/selector.h"
#include "ns3/rapidnet-functions.h"

using namespace std;
using namespace ns3;
using namespace ns3::rapidnet;
using namespace ns3::rapidnet::pktfwdsdn;

const string PktfwdSdn::DEVICE = "device";
const string PktfwdSdn::FLOWENTRY = "flowEntry";
const string PktfwdSdn::INITPACKET = "initPacket";
const string PktfwdSdn::LINK = "link";
const string PktfwdSdn::LINKHR = "linkhr";
const string PktfwdSdn::MATCHINGPACKET = "matchingPacket";
const string PktfwdSdn::MAXPRIORITY = "maxPriority";
const string PktfwdSdn::PACKET = "packet";
const string PktfwdSdn::RECVPACKET = "recvPacket";

NS_LOG_COMPONENT_DEFINE ("PktfwdSdn");
NS_OBJECT_ENSURE_REGISTERED (PktfwdSdn);

TypeId
PktfwdSdn::GetTypeId (void)
{
  static TypeId tid = TypeId ("ns3::rapidnet::pktfwdsdn::PktfwdSdn")
    .SetParent<RapidNetApplicationBase> ()
    .AddConstructor<PktfwdSdn> ()
    ;
  return tid;
}

PktfwdSdn::PktfwdSdn()
{
  NS_LOG_FUNCTION_NOARGS ();
}

PktfwdSdn::~PktfwdSdn()
{
  NS_LOG_FUNCTION_NOARGS ();
}

void
PktfwdSdn::DoDispose (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::DoDispose ();
}

void
PktfwdSdn::StartApplication (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StartApplication ();
  RAPIDNET_LOG_INFO("PktfwdSdn Application Started");
}

void
PktfwdSdn::StopApplication ()
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StopApplication ();
  RAPIDNET_LOG_INFO("PktfwdSdn Application Stopped");
}

void
PktfwdSdn::InitDatabase ()
{
  //RapidNetApplicationBase::InitDatabase ();

  AddRelationWithKeys (DEVICE, attrdeflist (
    attrdef ("device_attr2", INT32)));

  AddRelationWithKeys (FLOWENTRY, attrdeflist (
    attrdef ("flowEntry_attr2", IPV4),
    attrdef ("flowEntry_attr4", INT32)));

  AddRelationWithKeys (INITPACKET, attrdeflist (
    attrdef ("initPacket_attr2", IPV4),
    attrdef ("initPacket_attr3", IPV4),
    attrdef ("initPacket_attr4", STR)));

  AddRelationWithKeys (LINK, attrdeflist (
    attrdef ("link_attr2", IPV4)));

  AddRelationWithKeys (LINKHR, attrdeflist (
    attrdef ("linkhr_attr2", IPV4)));

  AddRelationWithKeys (MAXPRIORITY, attrdeflist (
    attrdef ("maxPriority_attr2", INT32)));

  AddRelationWithKeys (RECVPACKET, attrdeflist (
    attrdef ("recvPacket_attr2", IPV4),
    attrdef ("recvPacket_attr3", IPV4),
    attrdef ("recvPacket_attr4", STR)));

}

void
PktfwdSdn::DemuxRecv (Ptr<Tuple> tuple)
{
  RapidNetApplicationBase::DemuxRecv (tuple);

  if (IsRecvEvent (tuple, PACKET))
    {
      Rs1_eca (tuple);
    }
  if (IsRecvEvent (tuple, MATCHINGPACKET))
    {
      Rs2_eca (tuple);
    }
  if (IsRecvEvent (tuple, MATCHINGPACKET))
    {
      Rs3_eca (tuple);
    }
  if (IsRecvEvent (tuple, MATCHINGPACKET))
    {
      Rs4_eca (tuple);
    }
  if (IsInsertEvent (tuple, DEVICE))
    {
      Rh1Eca0Ins (tuple);
    }
  if (IsInsertEvent (tuple, INITPACKET))
    {
      Rh1Eca1Ins (tuple);
    }
  if (IsInsertEvent (tuple, LINKHR))
    {
      Rh1Eca2Ins (tuple);
    }
  if (IsRecvEvent (tuple, PACKET))
    {
      Rh2_eca (tuple);
    }
}

void
PktfwdSdn::Rs1_eca (Ptr<Tuple> packet)
{
  RAPIDNET_LOG_INFO ("Rs1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    packet,
    strlist ("device_attr1"),
    strlist ("packet_attr1"));

  result = GetRelation (MAXPRIORITY)->Join (
    result,
    strlist ("maxPriority_attr1"),
    strlist ("packet_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    MATCHINGPACKET,
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      "maxPriority_attr2"),
    strlist ("matchingPacket_attr1",
      "matchingPacket_attr2",
      "matchingPacket_attr3",
      "matchingPacket_attr4",
      "matchingPacket_attr5"));

  SendLocal (result);
}

void
PktfwdSdn::Rs2_eca (Ptr<Tuple> matchingPacket)
{
  RAPIDNET_LOG_INFO ("Rs2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    matchingPacket,
    strlist ("device_attr1"),
    strlist ("matchingPacket_attr1"));

  result = GetRelation (FLOWENTRY)->Join (
    result,
    strlist ("flowEntry_attr4", "flowEntry_attr1"),
    strlist ("matchingPacket_attr5", "matchingPacket_attr1"));

  result->Assign (Assignor::New ("NextPriority",
    Operation::New (RN_MINUS,
      VarExpr::New ("matchingPacket_attr5"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Select (Selector::New (
    Operation::New (RN_GT,
      VarExpr::New ("matchingPacket_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Select (Selector::New (
    Operation::New (RN_NEQ,
      VarExpr::New ("matchingPacket_attr3"),
      VarExpr::New ("flowEntry_attr2"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    MATCHINGPACKET,
    strlist ("matchingPacket_attr1",
      "matchingPacket_attr2",
      "matchingPacket_attr3",
      "matchingPacket_attr4",
      "NextPriority"),
    strlist ("matchingPacket_attr1",
      "matchingPacket_attr2",
      "matchingPacket_attr3",
      "matchingPacket_attr4",
      "matchingPacket_attr5"));

  SendLocal (result);
}

void
PktfwdSdn::Rs3_eca (Ptr<Tuple> matchingPacket)
{
  RAPIDNET_LOG_INFO ("Rs3_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    matchingPacket,
    strlist ("device_attr1"),
    strlist ("matchingPacket_attr1"));

  result = GetRelation (FLOWENTRY)->Join (
    result,
    strlist ("flowEntry_attr4", "flowEntry_attr1"),
    strlist ("matchingPacket_attr5", "matchingPacket_attr1"));

  result = GetRelation (LINK)->Join (
    result,
    strlist ("link_attr2", "link_attr1"),
    strlist ("flowEntry_attr3", "matchingPacket_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_GT,
      VarExpr::New ("matchingPacket_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("matchingPacket_attr3"),
      VarExpr::New ("flowEntry_attr2"))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    PACKET,
    strlist ("flowEntry_attr3",
      "matchingPacket_attr2",
      "matchingPacket_attr3",
      "matchingPacket_attr4",
      "flowEntry_attr3"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      RN_DEST));

  Send (result);
}

void
PktfwdSdn::Rs4_eca (Ptr<Tuple> matchingPacket)
{
  RAPIDNET_LOG_INFO ("Rs4_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    matchingPacket,
    strlist ("device_attr1"),
    strlist ("matchingPacket_attr1"));

  result = GetRelation (FLOWENTRY)->Join (
    result,
    strlist ("flowEntry_attr2", "flowEntry_attr4", "flowEntry_attr1"),
    strlist ("matchingPacket_attr3", "matchingPacket_attr5", "matchingPacket_attr1"));

  result = GetRelation (LINK)->Join (
    result,
    strlist ("link_attr2", "link_attr1"),
    strlist ("flowEntry_attr3", "matchingPacket_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("matchingPacket_attr5"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (0)))));

  result = result->Project (
    PACKET,
    strlist ("flowEntry_attr3",
      "matchingPacket_attr2",
      "matchingPacket_attr3",
      "matchingPacket_attr4",
      "flowEntry_attr3"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      RN_DEST));

  Send (result);
}

void
PktfwdSdn::Rh1Eca0Ins (Ptr<Tuple> device)
{
  RAPIDNET_LOG_INFO ("Rh1Eca0Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (INITPACKET)->Join (
    device,
    strlist ("initPacket_attr1"),
    strlist ("device_attr1"));

  result = GetRelation (LINKHR)->Join (
    result,
    strlist ("linkhr_attr1"),
    strlist ("device_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    PACKET,
    strlist ("linkhr_attr2",
      "initPacket_attr2",
      "initPacket_attr3",
      "initPacket_attr4",
      "linkhr_attr2"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      RN_DEST));

  Send (result);
}

void
PktfwdSdn::Rh1Eca1Ins (Ptr<Tuple> initPacket)
{
  RAPIDNET_LOG_INFO ("Rh1Eca1Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    initPacket,
    strlist ("device_attr1"),
    strlist ("initPacket_attr1"));

  result = GetRelation (LINKHR)->Join (
    result,
    strlist ("linkhr_attr1"),
    strlist ("initPacket_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    PACKET,
    strlist ("linkhr_attr2",
      "initPacket_attr2",
      "initPacket_attr3",
      "initPacket_attr4",
      "linkhr_attr2"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      RN_DEST));

  Send (result);
}

void
PktfwdSdn::Rh1Eca2Ins (Ptr<Tuple> linkhr)
{
  RAPIDNET_LOG_INFO ("Rh1Eca2Ins triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    linkhr,
    strlist ("device_attr1"),
    strlist ("linkhr_attr1"));

  result = GetRelation (INITPACKET)->Join (
    result,
    strlist ("initPacket_attr1"),
    strlist ("linkhr_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    PACKET,
    strlist ("linkhr_attr2",
      "initPacket_attr2",
      "initPacket_attr3",
      "initPacket_attr4",
      "linkhr_attr2"),
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4",
      RN_DEST));

  Send (result);
}

void
PktfwdSdn::Rh2_eca (Ptr<Tuple> packet)
{
  RAPIDNET_LOG_INFO ("Rh2_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (DEVICE)->Join (
    packet,
    strlist ("device_attr1"),
    strlist ("packet_attr1"));

  result = result->Select (Selector::New (
    Operation::New (RN_EQ,
      VarExpr::New ("device_attr2"),
      ValueExpr::New (Int32Value::New (1)))));

  result = result->Project (
    RECVPACKET,
    strlist ("packet_attr1",
      "packet_attr2",
      "packet_attr3",
      "packet_attr4"),
    strlist ("recvPacket_attr1",
      "recvPacket_attr2",
      "recvPacket_attr3",
      "recvPacket_attr4"));

  Insert (result);
}

