## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pktfwd-sdn', ['internet-stack'])
    module.source = [
        'pktfwd-sdn.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pktfwd-sdn'
    headers.source = [
        'pktfwd-sdn.h',
        'pktfwd-sdn-helper.h',
        ]
