## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('ml', ['internet-stack'])
    module.source = [
        'ml.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'ml'
    headers.source = [
        'ml.h',
        'ml-helper.h',
        ]
