## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pktfwd-norm-prov-oct0116', ['internet-stack'])
    module.source = [
        'pktfwd-norm-prov-oct0116.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pktfwd-norm-prov-oct0116'
    headers.source = [
        'pktfwd-norm-prov-oct0116.h',
        'pktfwd-norm-prov-oct0116-helper.h',
        ]
