## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pktfwd-norm-no-device', ['internet-stack'])
    module.source = [
        'pktfwd-norm-no-device.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pktfwd-norm-no-device'
    headers.source = [
        'pktfwd-norm-no-device.h',
        'pktfwd-norm-no-device-helper.h',
        ]
