## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pktfwd-norm-dist-hlist-rmitm', ['internet-stack'])
    module.source = [
        'pktfwd-norm-dist-hlist-rmitm.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pktfwd-norm-dist-hlist-rmitm'
    headers.source = [
        'pktfwd-norm-dist-hlist-rmitm.h',
        'pktfwd-norm-dist-hlist-rmitm-helper.h',
        ]
